import type { CatalogWidget } from './catalog.js'
import { DATA_CATALOG } from './catalog.js'

export const CATALOG_WIDGETS: CatalogWidget[] = [
  // ─── BID CÂMBIO ───────────────────────────────────────────────────
  {
    id: 'bid-cambio.saving_total',
    title: 'Saving Total (R$)',
    description: 'Soma total de saving gerado em operações de câmbio no período',
    productId: 'bid-cambio',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-cambio.saving_total'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-cambio.valor_operado',
    title: 'Valor Operado (R$)',
    description: 'Valor total operado em câmbio no período selecionado',
    productId: 'bid-cambio',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-cambio.valor_operado'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-cambio.cotacoes_status',
    title: 'Cotações por Status',
    description: 'Distribuição das cotações de câmbio agrupadas por status atual',
    productId: 'bid-cambio',
    chartType: 'DONUT',
    querySpec: { fields: ['bid-cambio.cotacoes_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'bid-cambio.taxa_resposta',
    title: 'Taxa de Resposta (%)',
    description: 'Percentual médio de resposta das corretoras às cotações enviadas',
    productId: 'bid-cambio',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-cambio.taxa_resposta'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'bid-cambio.economia_percentual',
    title: 'Economia Média (%)',
    description: 'Percentual médio de economia obtido nas operações de câmbio',
    productId: 'bid-cambio',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-cambio.economia_percentual'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-cambio.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de cotações de câmbio mês a mês',
    productId: 'bid-cambio',
    chartType: 'LINE',
    querySpec: { fields: ['bid-cambio.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },

  // ─── BID FRETE ────────────────────────────────────────────────────
  {
    id: 'bid-frete.saving_total',
    title: 'Saving Total (R$)',
    description: 'Soma total de saving gerado em cotações de frete no período',
    productId: 'bid-frete',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-frete.saving_total'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-frete.valor_medio',
    title: 'Valor Médio de Frete',
    description: 'Valor médio dos fretes contratados no período selecionado',
    productId: 'bid-frete',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-frete.valor_medio'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-frete.cotacoes_status',
    title: 'Cotações por Status',
    description: 'Distribuição das cotações de frete agrupadas por status atual',
    productId: 'bid-frete',
    chartType: 'DONUT',
    querySpec: { fields: ['bid-frete.cotacoes_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'bid-frete.saving_percentual',
    title: 'Saving Médio (%)',
    description: 'Percentual médio de saving obtido nas cotações de frete',
    productId: 'bid-frete',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-frete.saving_percentual'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'bid-frete.transit_time',
    title: 'Prazo Médio (dias)',
    description: 'Prazo médio de trânsito das cotações de frete contratadas',
    productId: 'bid-frete',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['bid-frete.transit_time'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'bid-frete.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de cotações de frete mês a mês',
    productId: 'bid-frete',
    chartType: 'LINE',
    querySpec: { fields: ['bid-frete.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },

  // ─── FINANCEIRO COMEX ─────────────────────────────────────────────
  {
    id: 'fin-comex.total_brl',
    title: 'Total (R$)',
    description: 'Valor total consolidado de todas as transações financeiras no período',
    productId: 'financeiro-comex',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['fin-comex.total_brl'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'fin-comex.pendente',
    title: 'Pendente (R$)',
    description: 'Valor total de pagamentos ainda pendentes de quitação',
    productId: 'financeiro-comex',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['fin-comex.pendente'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'fin-comex.pagos',
    title: 'Pago (R$)',
    description: 'Valor total de pagamentos já quitados no período selecionado',
    productId: 'financeiro-comex',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['fin-comex.pagos'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'fin-comex.agendados',
    title: 'Agendado (R$)',
    description: 'Valor total de pagamentos agendados para datas futuras',
    productId: 'financeiro-comex',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['fin-comex.agendados'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'fin-comex.por_moeda',
    title: 'Por Moeda',
    description: 'Distribuição dos valores financeiros agrupados por moeda de origem',
    productId: 'financeiro-comex',
    chartType: 'DONUT',
    querySpec: { fields: ['fin-comex.por_moeda'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'fin-comex.vencimentos_proximos',
    title: 'Vencimentos Próximos',
    description: 'Quantidade de pagamentos com vencimento nos próximos dias',
    productId: 'financeiro-comex',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['fin-comex.vencimentos_proximos'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },

  // ─── PROCESSO ────────────────────────────────────────────────────
  {
    id: 'processo.total_ativos',
    title: 'Processos Ativos',
    description: 'Quantidade total de processos de importação em andamento',
    productId: 'processo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['processo.total_ativos'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'processo.atraso_chegada',
    title: 'Atraso Médio (dias)',
    description: 'Atraso médio em dias entre a data prevista e real de chegada dos processos',
    productId: 'processo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['processo.atraso_chegada'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'processo.etapas_atrasadas',
    title: 'Etapas Atrasadas',
    description: 'Quantidade de etapas de processos que estão em atraso no momento',
    productId: 'processo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['processo.etapas_atrasadas'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'processo.por_status',
    title: 'Por Status',
    description: 'Distribuição dos processos de importação agrupados por status atual',
    productId: 'processo',
    chartType: 'DONUT',
    querySpec: { fields: ['processo.por_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'processo.chegadas_7d',
    title: 'Chegando em 7 dias',
    description: 'Quantidade de processos com previsão de chegada nos próximos 7 dias',
    productId: 'processo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['processo.chegadas_7d'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'processo.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de processos de importação abertos mês a mês',
    productId: 'processo',
    chartType: 'LINE',
    querySpec: { fields: ['processo.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },

  // ─── PEDIDO ───────────────────────────────────────────────────────
  {
    id: 'pedido.total_abertos',
    title: 'Pedidos Abertos',
    description: 'Quantidade total de pedidos de importação em aberto no momento',
    productId: 'pedido',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['pedido.total_abertos'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'pedido.valor_fob_total',
    title: 'Valor FOB Total',
    description: 'Soma do valor FOB de todos os pedidos de importação no período',
    productId: 'pedido',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['pedido.valor_fob_total'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'pedido.por_status',
    title: 'Por Status',
    description: 'Distribuição dos pedidos de importação agrupados por status atual',
    productId: 'pedido',
    chartType: 'DONUT',
    querySpec: { fields: ['pedido.por_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'pedido.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de pedidos de importação criados mês a mês',
    productId: 'pedido',
    chartType: 'LINE',
    querySpec: { fields: ['pedido.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'pedido.itens_ncm',
    title: 'Itens por NCM',
    description: 'Distribuição dos itens de pedidos agrupados por código NCM',
    productId: 'pedido',
    chartType: 'BAR',
    querySpec: { fields: ['pedido.itens_ncm'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'pedido.valor_por_fornecedor',
    title: 'Valor por Fornecedor',
    description: 'Distribuição do valor FOB por fornecedor no período selecionado',
    productId: 'pedido',
    chartType: 'BAR_HORIZONTAL',
    querySpec: { fields: ['pedido.valor_por_fornecedor'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'financeiro',
  },

  // ─── NF IMPORTAÇÃO ────────────────────────────────────────────────
  {
    id: 'nf-imp.total_fob',
    title: 'Total FOB (R$)',
    description: 'Soma total do valor FOB das notas fiscais de importação no período',
    productId: 'nf-importacao',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['nf-imp.total_fob'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'nf-imp.total_cif',
    title: 'Total CIF (R$)',
    description: 'Soma total do valor CIF das notas fiscais de importação no período',
    productId: 'nf-importacao',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['nf-imp.total_cif'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'nf-imp.total_tributos',
    title: 'Total Tributos (R$)',
    description: 'Soma total de tributos pagos nas notas fiscais de importação',
    productId: 'nf-importacao',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['nf-imp.total_tributos'], operation: 'sum', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'nf-imp.nfs_por_status',
    title: 'NFs por Status',
    description: 'Distribuição das notas fiscais de importação agrupadas por status',
    productId: 'nf-importacao',
    chartType: 'DONUT',
    querySpec: { fields: ['nf-imp.nfs_por_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'nf-imp.tributos_breakdown',
    title: 'Breakdown de Tributos',
    description: 'Composição dos tributos por tipo (II, IPI, PIS, COFINS, ICMS) nas NFs',
    productId: 'nf-importacao',
    chartType: 'BAR_HORIZONTAL',
    querySpec: { fields: ['nf-imp.tributos_breakdown'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'financeiro',
  },
  {
    id: 'nf-imp.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de notas fiscais de importação emitidas mês a mês',
    productId: 'nf-importacao',
    chartType: 'LINE',
    querySpec: { fields: ['nf-imp.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },

  // ─── SIMULA CUSTO ────────────────────────────────────────────────
  {
    id: 'simula-custo.landed_cost_medio',
    title: 'Landed Cost Médio (R$)',
    description: 'Custo de importação médio (landed cost) das estimativas no período',
    productId: 'simula-custo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['simula-custo.landed_cost_medio'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'simula-custo.estimativas_ativas',
    title: 'Estimativas Ativas',
    description: 'Quantidade de simulações de custo de importação ativas no momento',
    productId: 'simula-custo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['simula-custo.estimativas_ativas'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'simula-custo.total_tributos_medio',
    title: 'Tributos Médios (R$)',
    description: 'Valor médio de tributos calculados nas simulações de custo',
    productId: 'simula-custo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['simula-custo.total_tributos_medio'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'financeiro',
  },
  {
    id: 'simula-custo.tributos_breakdown',
    title: 'Breakdown de Tributos',
    description: 'Composição dos tributos simulados por tipo nas estimativas de custo',
    productId: 'simula-custo',
    chartType: 'DONUT',
    querySpec: { fields: ['simula-custo.tributos_breakdown'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'financeiro',
  },
  {
    id: 'simula-custo.ptax_media',
    title: 'PTAX Média',
    description: 'Taxa PTAX média utilizada nas simulações de custo no período',
    productId: 'simula-custo',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['simula-custo.ptax_media'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'simula-custo.volume_mensal',
    title: 'Volume Mensal',
    description: 'Evolução do volume de simulações de custo criadas mês a mês',
    productId: 'simula-custo',
    chartType: 'LINE',
    querySpec: { fields: ['simula-custo.volume_mensal'], operation: 'count', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },

  // ─── LPCO ─────────────────────────────────────────────────────────
  {
    id: 'lpco.total_ativo',
    title: 'LPCOs Ativos',
    description: 'Quantidade total de licenças, permissões, certificados e outros documentos ativos',
    productId: 'lpco',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['lpco.total_ativo'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'lpco.vencendo_30d',
    title: 'Vencendo em 30 dias',
    description: 'Quantidade de LPCOs com data de validade nos próximos 30 dias',
    productId: 'lpco',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['lpco.vencendo_30d'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'lpco.exigencias_pendentes',
    title: 'Exigências Pendentes',
    description: 'Quantidade de exigências de órgãos anuentes ainda não atendidas',
    productId: 'lpco',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['lpco.exigencias_pendentes'], operation: 'count', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
  {
    id: 'lpco.por_orgao',
    title: 'Por Órgão Anuente',
    description: 'Distribuição dos LPCOs agrupados por órgão anuente responsável',
    productId: 'lpco',
    chartType: 'DONUT',
    querySpec: { fields: ['lpco.por_orgao'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'lpco.por_status',
    title: 'Por Status',
    description: 'Distribuição dos LPCOs agrupados por status do documento',
    productId: 'lpco',
    chartType: 'DONUT',
    querySpec: { fields: ['lpco.por_status'], operation: 'distribution', filters: { period: '30d' } },
    size: 'md',
    category: 'operacional',
  },
  {
    id: 'lpco.taxa_deferimento',
    title: 'Taxa de Deferimento (%)',
    description: 'Percentual médio de deferimento das solicitações de LPCO pelos órgãos',
    productId: 'lpco',
    chartType: 'KPI_CARD',
    querySpec: { fields: ['lpco.taxa_deferimento'], operation: 'avg', filters: { period: '30d' } },
    size: 'sm',
    category: 'operacional',
  },
]

/** Retorna widgets pré-construídos de um produto específico */
export function getWidgetsForProduct(productId: string): CatalogWidget[] {
  return CATALOG_WIDGETS.filter(w => w.productId === productId)
}

/** Retorna widgets pré-construídos filtrados pelas permissões do usuário */
export function getWidgetsForUser(userPermissions: string[]): CatalogWidget[] {
  const allowedKeys = new Set(
    DATA_CATALOG
      .filter(f => userPermissions.includes(f.permission))
      .map(f => f.key)
  )
  return CATALOG_WIDGETS.filter(w =>
    w.querySpec.fields.every(field => allowedKeys.has(field))
  )
}

/** Busca um widget pelo seu id */
export function findWidget(id: string): CatalogWidget | undefined {
  return CATALOG_WIDGETS.find(w => w.id === id)
}
