/**
 * catalogo-colunas-documento-smart-read.ts — GERADO AUTOMATICAMENTE. NÃO EDITAR À MÃO.
 *
 * Fonte: catalogar-campos/mapeamento-campos-completo.csv
 * Gerador: catalogar-campos/gerar-catalogo-colunas-documento-smart-read.ts
 *
 * Catálogo de colunas possíveis na lista do Smart Read, consolidado por campo de
 * negócio (`key` = campo_gravity). Cada coluna conhece em quais tipos de documento
 * aparece (`tipos`) e quais caminhos do JSON legado a alimentam (`caminhos`).
 *
 * Total: 245 colunas · 5 tipos de documento.
 */

export type TipoDocumentoSmartRead = "AWB" | "BL" | "FINANCIAL_DOCUMENT" | "INVOICE" | "PACKING_LIST"

export type StatusMapeamentoColunaSmartRead = 'mapeado' | 'pendente'

export type ColunaDocumentoCatalogoSmartRead = {
  /** Id estável da coluna (campo_gravity DDD). */
  key: string
  /** Rótulo exibido no cabeçalho/seletor. */
  label: string
  /** Seção de agrupamento (Exportador, Mercadorias, Taxas…). */
  secao: string
  /** Tipos de documento em que a coluna aparece. */
  tipos: string[]
  /** Caminhos canônicos no JSON legado que alimentam o valor da coluna. */
  caminhos: string[]
  /** `mapeado` (regra DDD validada) ou `pendente` (slug automático). */
  status: StatusMapeamentoColunaSmartRead
}

export const CATALOGO_COLUNAS_DOCUMENTO_SMART_READ: ColunaDocumentoCatalogoSmartRead[] = [
  { key: "campo_adicional_agente_de_entrega", label: "Agente de Entrega", secao: "Campos adicionais", tipos: ["BL"], caminhos: ["additionalFields.Agente de Entrega"], status: "mapeado" },
  { key: "campo_adicional_assinado_por", label: "Assinado por", secao: "Campos adicionais", tipos: ["AWB"], caminhos: ["additionalFields.Assinado por"], status: "mapeado" },
  { key: "campo_adicional_cnpj_agente_de_entrega", label: "CNPJ Agente de Entrega", secao: "Campos adicionais", tipos: ["BL"], caminhos: ["additionalFields.CNPJ Agente de Entrega"], status: "mapeado" },
  { key: "campo_adicional_codigo_do_cliente", label: "Código do Cliente", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Código do Cliente"], status: "mapeado" },
  { key: "campo_adicional_contato_importador", label: "Contato Importador", secao: "Campos adicionais", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["additionalFields.Contato Importador"], status: "mapeado" },
  { key: "campo_adicional_data_de_vencimento", label: "Data de Vencimento", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Data de Vencimento"], status: "mapeado" },
  { key: "campo_adicional_dimensoes", label: "Dimensões", secao: "Campos adicionais", tipos: ["PACKING_LIST"], caminhos: ["additionalFields.Dimensões"], status: "mapeado" },
  { key: "campo_adicional_email_agente_de_entrega", label: "Email Agente de Entrega", secao: "Campos adicionais", tipos: ["BL"], caminhos: ["additionalFields.Email Agente de Entrega"], status: "mapeado" },
  { key: "campo_adicional_fabricante", label: "Fabricante", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Fabricante"], status: "mapeado" },
  { key: "campo_adicional_nota_de_entrega", label: "Nota de Entrega", secao: "Campos adicionais", tipos: ["PACKING_LIST"], caminhos: ["additionalFields.Nota de Entrega"], status: "mapeado" },
  { key: "campo_adicional_numero_de_referencia", label: "Número de Referência", secao: "Campos adicionais", tipos: ["AWB"], caminhos: ["additionalFields.Número de Referência"], status: "mapeado" },
  { key: "campo_adicional_ordem_de_trabalho", label: "Ordem de Trabalho", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Ordem de Trabalho"], status: "mapeado" },
  { key: "campo_adicional_outras_taxas", label: "Outras Taxas", secao: "Campos adicionais", tipos: ["AWB"], caminhos: ["additionalFields.Outras Taxas"], status: "mapeado" },
  { key: "campo_adicional_pais_de_aquisicao", label: "País de Aquisição", secao: "Campos adicionais", tipos: ["PACKING_LIST"], caminhos: ["additionalFields.País de Aquisição"], status: "mapeado" },
  { key: "campo_adicional_pais_de_procedencia", label: "País de Procedência", secao: "Campos adicionais", tipos: ["PACKING_LIST"], caminhos: ["additionalFields.País de Procedência"], status: "mapeado" },
  { key: "campo_adicional_porto_de_entrega", label: "Porto de Entrega", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Porto de Entrega"], status: "mapeado" },
  { key: "campo_adicional_subtotal", label: "Subtotal", secao: "Campos adicionais", tipos: ["INVOICE"], caminhos: ["additionalFields.Subtotal"], status: "mapeado" },
  { key: "campo_adicional_total_de_paletes", label: "Total de Paletes", secao: "Campos adicionais", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["additionalFields.Total de Paletes"], status: "mapeado" },
  { key: "campo_adicional_vendedor_beneficiario", label: "Vendedor Beneficiário", secao: "Campos adicionais", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["additionalFields.Vendedor Beneficiário"], status: "mapeado" },
  { key: "indicador_carga_perigosa_containers", label: "Carga perigosa (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].dangerous_goods_indicator"], status: "mapeado" },
  { key: "classe_carga_perigosa_containers", label: "Classe carga perigosa (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].dangerous_goods_class"], status: "mapeado" },
  { key: "containers[]_container_tare", label: "Container Tare", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_tare"], status: "pendente" },
  { key: "lacre_container_containers", label: "Lacre (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_seal"], status: "mapeado" },
  { key: "numero_container_containers", label: "Número do container (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_number"], status: "mapeado" },
  { key: "numeros_container_containers", label: "Números de container (Containers)", secao: "Containers", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["containerNumbers"], status: "mapeado" },
  { key: "peso_bruto_container_containers", label: "Peso bruto container (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_gross_weight"], status: "mapeado" },
  { key: "peso_liquido_container_containers", label: "Peso líquido container (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_net_weight"], status: "mapeado" },
  { key: "quantidade_embalagem_containers", label: "Quantidade embalagem (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].packaging[].quantity"], status: "mapeado" },
  { key: "tipo_container_containers", label: "Tipo do container (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_type"], status: "mapeado" },
  { key: "tipo_embalagem_containers", label: "Tipo embalagem (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].packaging[].type"], status: "mapeado" },
  { key: "volume_container_containers", label: "Volume container (Containers)", secao: "Containers", tipos: ["BL"], caminhos: ["containers[].container_volume"], status: "mapeado" },
  { key: "bankingdetails_accountnumber", label: "Account Number", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.accountNumber"], status: "pendente" },
  { key: "bankingdetails_beneficiary", label: "Beneficiary", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.beneficiary"], status: "pendente" },
  { key: "bankingdetails_branchcode", label: "Branch Code", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.branchCode"], status: "pendente" },
  { key: "bankingdetails_fulltext", label: "Full Text", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.fullText"], status: "pendente" },
  { key: "iban_dados_bancarios", label: "IBAN (Dados bancários)", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.iban"], status: "mapeado" },
  { key: "nome_banco_dados_bancarios", label: "Nome do banco (Dados bancários)", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.bankName"], status: "mapeado" },
  { key: "swift_dados_bancarios", label: "SWIFT (Dados bancários)", secao: "Dados bancários", tipos: ["INVOICE"], caminhos: ["bankingDetails.swift"], status: "mapeado" },
  { key: "data_documento", label: "Data do documento (Documento)", secao: "Documento", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["document.date", "document.documentDate"], status: "mapeado" },
  { key: "data_embarque_documento", label: "Data shipped on board (Documento)", secao: "Documento", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["document.shippedOnBoardDate"], status: "mapeado" },
  { key: "documento_assinado_documento", label: "Documento assinado (Documento)", secao: "Documento", tipos: ["AWB", "BL", "FINANCIAL_DOCUMENT", "INVOICE", "PACKING_LIST"], caminhos: ["isSigned"], status: "mapeado" },
  { key: "incoterm_documento", label: "Incoterm (Documento)", secao: "Documento", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["document.incoterm"], status: "mapeado" },
  { key: "local_incoterm_documento", label: "Local incoterm (Documento)", secao: "Documento", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["document.incotermLocation"], status: "mapeado" },
  { key: "numero_bl_documento", label: "Número do BL (Documento)", secao: "Documento", tipos: ["BL"], caminhos: ["document.billOfLadingNumber"], status: "mapeado" },
  { key: "numero_bl_master_documento", label: "Número do BL master (Documento)", secao: "Documento", tipos: ["BL"], caminhos: ["document.masterBillOfLadingNumber"], status: "mapeado" },
  { key: "numero_documento", label: "Número do documento (Documento)", secao: "Documento", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["document.documentNumber", "document.number"], status: "mapeado" },
  { key: "pais_aquisicao_documento", label: "País de aquisição (Documento)", secao: "Documento", tipos: ["INVOICE"], caminhos: ["document.countryOfAcquisition"], status: "mapeado" },
  { key: "pais_origem_documento", label: "País de origem (Documento)", secao: "Documento", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["document.originCountry"], status: "mapeado" },
  { key: "pais_procedencia_documento", label: "País de procedência (Documento)", secao: "Documento", tipos: ["INVOICE"], caminhos: ["document.countryOfProvenance"], status: "mapeado" },
  { key: "referencia_booking_documento", label: "Referência booking (Documento)", secao: "Documento", tipos: ["BL"], caminhos: ["document.bookingReference"], status: "mapeado" },
  { key: "tipo_documento", label: "Tipo do documento (Documento)", secao: "Documento", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["document.documentType", "document.type"], status: "mapeado" },
  { key: "shipmentdetails_destination_airport", label: "Airport", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.destination.airport"], status: "pendente" },
  { key: "shipmentdetails_origin_airport", label: "Airport", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.origin.airport"], status: "pendente" },
  { key: "shipmentdetails_cargodescription", label: "Cargo Description", secao: "Embarque", tipos: ["AWB"], caminhos: ["shipmentDetails.cargoDescription"], status: "pendente" },
  { key: "shipment_airports_destination", label: "Destination", secao: "Embarque", tipos: ["INVOICE"], caminhos: ["shipment.airports.destination"], status: "pendente" },
  { key: "estado_destino_embarque", label: "Estado destino (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.destination_state"], status: "mapeado" },
  { key: "valor_frete_embarque", label: "Frete (Embarque)", secao: "Embarque", tipos: ["INVOICE"], caminhos: ["shipment.costs.freight"], status: "mapeado" },
  { key: "local_destino_embarque", label: "Local destino (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.place_of_destination"], status: "mapeado" },
  { key: "local_origem_embarque", label: "Local origem (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.place_of_origin"], status: "mapeado" },
  { key: "shipmentdetails_destination_location", label: "Location", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.destination.location"], status: "pendente" },
  { key: "shipmentdetails_origin_location", label: "Location", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.origin.location"], status: "pendente" },
  { key: "marcas_numeros_embarque", label: "Marcas e números (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.marksAndNumbers"], status: "mapeado" },
  { key: "modal_transporte_embarque", label: "Modal de transporte (Embarque)", secao: "Embarque", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["shipment.modal", "shipmentDetails.transportMode"], status: "mapeado" },
  { key: "nome_navio_embarque", label: "Nome do navio (Embarque)", secao: "Embarque", tipos: ["BL", "INVOICE"], caminhos: ["shipment.vesselName", "shipment.vessel_name"], status: "mapeado" },
  { key: "numero_viagem_embarque", label: "Número da viagem (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.voyage_number"], status: "mapeado" },
  { key: "shipment_airports_origin", label: "Origin", secao: "Embarque", tipos: ["INVOICE"], caminhos: ["shipment.airports.origin"], status: "pendente" },
  { key: "pais_origem_embarque_embarque", label: "País origem embarque (Embarque)", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.origin_country"], status: "mapeado" },
  { key: "shipmentdetails_destination_place", label: "Place", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.destination.place"], status: "pendente" },
  { key: "shipmentdetails_origin_place", label: "Place", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.origin.place"], status: "pendente" },
  { key: "shipmentdetails_destination_port", label: "Port", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.destination.port"], status: "pendente" },
  { key: "shipmentdetails_origin_port", label: "Port", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.origin.port"], status: "pendente" },
  { key: "porto_destino_embarque", label: "Porto destino (Embarque)", secao: "Embarque", tipos: ["BL", "INVOICE"], caminhos: ["shipment.port_of_destination", "shipment.ports.destination", "shipment.ports.discharge"], status: "mapeado" },
  { key: "porto_origem_embarque", label: "Porto origem (Embarque)", secao: "Embarque", tipos: ["BL", "INVOICE"], caminhos: ["shipment.port_of_origin", "shipment.ports.loading", "shipment.ports.origin"], status: "mapeado" },
  { key: "shipment_pre_carriage", label: "Pre Carriage", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.pre_carriage"], status: "pendente" },
  { key: "valor_seguro_embarque", label: "Seguro (Embarque)", secao: "Embarque", tipos: ["INVOICE"], caminhos: ["shipment.costs.insurance"], status: "mapeado" },
  { key: "shipmentdetails_tariffclass", label: "Tariff Class", secao: "Embarque", tipos: ["AWB"], caminhos: ["shipmentDetails.tariffClass"], status: "pendente" },
  { key: "shipment_temperature", label: "Temperature", secao: "Embarque", tipos: ["BL"], caminhos: ["shipment.temperature"], status: "pendente" },
  { key: "shipmentdetails_totalcubedweight", label: "Total Cubed Weight", secao: "Embarque", tipos: ["AWB"], caminhos: ["shipmentDetails.totalCubedWeight"], status: "pendente" },
  { key: "shipmentdetails_totalgrossweight", label: "Total Gross Weight", secao: "Embarque", tipos: ["AWB"], caminhos: ["shipmentDetails.totalGrossWeight"], status: "pendente" },
  { key: "shipmentdetails_totalpackages", label: "Total Packages", secao: "Embarque", tipos: ["AWB"], caminhos: ["shipmentDetails.totalPackages"], status: "pendente" },
  { key: "transportadora_embarque", label: "Transportadora (Embarque)", secao: "Embarque", tipos: ["INVOICE"], caminhos: ["shipment.carrier"], status: "mapeado" },
  { key: "shipmentdetails_vesselname", label: "Vessel Name", secao: "Embarque", tipos: ["PACKING_LIST"], caminhos: ["shipmentDetails.vesselName"], status: "pendente" },
  { key: "cep_exportador", label: "CEP / Código postal (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.zipCode", "exporter.zip_code"], status: "mapeado" },
  { key: "cidade_exportador", label: "Cidade (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.city"], status: "mapeado" },
  { key: "documento_fiscal_exportador", label: "CNPJ / Tax ID (Exportador)", secao: "Exportador", tipos: ["BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.taxId"], status: "mapeado" },
  { key: "email_exportador", label: "E-mail (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.email"], status: "mapeado" },
  { key: "endereco_exportador", label: "Endereço (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.address"], status: "mapeado" },
  { key: "estado_exportador", label: "Estado / UF (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.state", "exporter.state_province"], status: "mapeado" },
  { key: "nome_exportador", label: "Nome (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.name"], status: "mapeado" },
  { key: "pais_exportador", label: "País (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.country"], status: "mapeado" },
  { key: "telefone_exportador", label: "Telefone (Exportador)", secao: "Exportador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["exporter.phone"], status: "mapeado" },
  { key: "cep_importador", label: "CEP / Código postal (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.zipCode", "importer.zip_code"], status: "mapeado" },
  { key: "cidade_importador", label: "Cidade (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.city"], status: "mapeado" },
  { key: "cnpj_importador", label: "CNPJ (Importador)", secao: "Importador", tipos: ["AWB", "BL", "PACKING_LIST"], caminhos: ["importer.cnpj"], status: "mapeado" },
  { key: "documento_fiscal_importador", label: "CNPJ / Tax ID (Importador)", secao: "Importador", tipos: ["INVOICE"], caminhos: ["importer.taxId"], status: "mapeado" },
  { key: "email_importador", label: "E-mail (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.email"], status: "mapeado" },
  { key: "endereco_importador", label: "Endereço (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.address"], status: "mapeado" },
  { key: "estado_importador", label: "Estado / UF (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.state", "importer.state_province"], status: "mapeado" },
  { key: "nome_importador", label: "Nome (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.name"], status: "mapeado" },
  { key: "pais_importador", label: "País (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.country"], status: "mapeado" },
  { key: "telefone_importador", label: "Telefone (Importador)", secao: "Importador", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["importer.phone"], status: "mapeado" },
  { key: "items[]_additionalinformation", label: "Additional Information", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].additionalInformation"], status: "pendente" },
  { key: "items[]_volume_dimensions", label: "Dimensions", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].volume.dimensions"], status: "pendente" },
  { key: "items[]_descriptions_english", label: "English", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].descriptions.english"], status: "pendente" },
  { key: "items[]_weights_gross", label: "Gross", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].weights.gross"], status: "pendente" },
  { key: "hs_code_itens", label: "HS Code (Itens)", secao: "Itens", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["items[].hsCode"], status: "mapeado" },
  { key: "items[]_itemcurrency", label: "Item Currency", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].itemCurrency"], status: "pendente" },
  { key: "items[]_itemquantity", label: "Item Quantity", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].itemQuantity"], status: "pendente" },
  { key: "items[]_itemtotalpricewithcurrency", label: "Item Total Price With Currency", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].itemTotalPriceWithCurrency"], status: "pendente" },
  { key: "items[]_itemunitpricewithcurrency", label: "Item Unit Price With Currency", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].itemUnitPriceWithCurrency"], status: "pendente" },
  { key: "items[]_manufacturer", label: "Manufacturer", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].manufacturer"], status: "pendente" },
  { key: "ncm_itens", label: "NCM (Itens)", secao: "Itens", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["items[].ncm"], status: "mapeado" },
  { key: "items[]_weights_net", label: "Net", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].weights.net"], status: "pendente" },
  { key: "items[]_origincountry", label: "Origin Country", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].originCountry"], status: "pendente" },
  { key: "items[]_volume_packagetype", label: "Package Type", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].volume.packageType"], status: "pendente" },
  { key: "items[]_partnumber", label: "Part Number", secao: "Itens", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["items[].partNumber"], status: "pendente" },
  { key: "items[]_ponumber", label: "Po Number", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].poNumber"], status: "pendente" },
  { key: "items[]_descriptions_portuguese", label: "Portuguese", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].descriptions.portuguese"], status: "pendente" },
  { key: "items[]_productdescription", label: "Product Description", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].productDescription"], status: "pendente" },
  { key: "items[]_volume_quantity", label: "Quantity", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].volume.quantity"], status: "pendente" },
  { key: "items[]_volume_size", label: "Size", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].volume.size"], status: "pendente" },
  { key: "items[]_package_totalcubicmeasurement", label: "Total Cubic Measurement", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.totalCubicMeasurement"], status: "pendente" },
  { key: "items[]_totalproductquantity", label: "Total Product Quantity", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].totalProductQuantity"], status: "pendente" },
  { key: "items[]_package_totaltareweight", label: "Total Tare Weight", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.totalTareWeight"], status: "pendente" },
  { key: "items[]_package_type", label: "Type", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.type"], status: "pendente" },
  { key: "items[]_weights_unit", label: "Unit", secao: "Itens", tipos: ["INVOICE"], caminhos: ["items[].weights.unit"], status: "pendente" },
  { key: "items[]_package_unitgrossweight", label: "Unit Gross Weight", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.unitGrossWeight"], status: "pendente" },
  { key: "items[]_package_unitnetweight", label: "Unit Net Weight", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.unitNetWeight"], status: "pendente" },
  { key: "items[]_package_unitquantity", label: "Unit Quantity", secao: "Itens", tipos: ["PACKING_LIST"], caminhos: ["items[].package.unitQuantity"], status: "pendente" },
  { key: "descricao_bl_mercadorias", label: "Descrição BL (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.bl_description"], status: "mapeado" },
  { key: "descricao_item_mercadorias", label: "Descrição item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].description"], status: "mapeado" },
  { key: "hs_code_mercadorias", label: "HS Code (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.hs_code"], status: "mapeado" },
  { key: "invoice_item_mercadorias", label: "Invoice item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].invoice"], status: "mapeado" },
  { key: "ncm_mercadorias", label: "NCM (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].ncm", "goods.ncm_code"], status: "mapeado" },
  { key: "goods_ncm_list[]", label: "Ncm List[]", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.ncm_list[]"], status: "pendente" },
  { key: "peso_bruto_item_mercadorias", label: "Peso bruto item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].gross_weight"], status: "mapeado" },
  { key: "peso_bruto_total_mercadorias", label: "Peso bruto total (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.shipment_gross_weight"], status: "mapeado" },
  { key: "peso_liquido_item_mercadorias", label: "Peso líquido item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].net_weight"], status: "mapeado" },
  { key: "peso_liquido_total_mercadorias", label: "Peso líquido total (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.shipment_net_weight"], status: "mapeado" },
  { key: "quantidade_embalagem_resumo_mercadorias", label: "Qtd embalagem (resumo) (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.packaging_summary[].total_quantity"], status: "mapeado" },
  { key: "quantidade_item_mercadorias", label: "Quantidade item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].quantity"], status: "mapeado" },
  { key: "shipper_item_mercadorias", label: "Shipper item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].shipper"], status: "mapeado" },
  { key: "tipo_embalagem_resumo_mercadorias", label: "Tipo embalagem (resumo) (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.packaging_summary[].type"], status: "mapeado" },
  { key: "total_volumes_mercadorias", label: "Total de volumes (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.total_packages"], status: "mapeado" },
  { key: "unidade_volume_cubico_mercadorias", label: "Unidade cubagem (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.volume_unit"], status: "mapeado" },
  { key: "unidade_volume_mercadorias", label: "Unidade de volume (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.package_unit"], status: "mapeado" },
  { key: "volume_item_mercadorias", label: "Volume item (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.items[].volume"], status: "mapeado" },
  { key: "volume_total_mercadorias", label: "Volume total (Mercadorias)", secao: "Mercadorias", tipos: ["BL"], caminhos: ["goods.total_shipment_volume"], status: "mapeado" },
  { key: "moeda_moeda", label: "Moeda (Moeda)", secao: "Moeda", tipos: ["INVOICE"], caminhos: ["currency.type"], status: "mapeado" },
  { key: "taxa_cambio_moeda", label: "Taxa de câmbio (Moeda)", secao: "Moeda", tipos: ["INVOICE"], caminhos: ["currency.exchangeRate"], status: "mapeado" },
  { key: "cep_notify_party", label: "CEP / Código postal (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.zip_code"], status: "mapeado" },
  { key: "cidade_notify_party", label: "Cidade (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.city"], status: "mapeado" },
  { key: "cnpj_notify_party", label: "CNPJ (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.cnpj"], status: "mapeado" },
  { key: "email_notify_party", label: "E-mail (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.email"], status: "mapeado" },
  { key: "endereco_notify_party", label: "Endereço (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.address"], status: "mapeado" },
  { key: "estado_notify_party", label: "Estado / UF (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.state_province"], status: "mapeado" },
  { key: "nome_notify_party", label: "Nome (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.name"], status: "mapeado" },
  { key: "pais_notify_party", label: "País (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.country"], status: "mapeado" },
  { key: "telefone_notify_party", label: "Telefone (Notify party)", secao: "Notify party", tipos: ["BL"], caminhos: ["notify_party.phone"], status: "mapeado" },
  { key: "observacoes_observacoes", label: "Observações (Observações)", secao: "Observações", tipos: ["AWB", "BL", "INVOICE", "PACKING_LIST"], caminhos: ["observations"], status: "mapeado" },
  { key: "abatimentos", label: "Abatimentos", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Abatimentos"], status: "pendente" },
  { key: "cargoagent_accountinginfo", label: "Accounting Info", secao: "Outros", tipos: ["AWB"], caminhos: ["cargoAgent.accountingInfo"], status: "pendente" },
  { key: "acréscimos", label: "AcréScimos", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Acréscimos"], status: "pendente" },
  { key: "agência e código do beneficiário", label: "AgêNcia E CóDigo Do BeneficiáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Agência e Código do Beneficiário"], status: "pendente" },
  { key: "awbinfo_awbdate", label: "Awb Date", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.awbDate"], status: "pendente" },
  { key: "freight_basic_value", label: "Basic Value", secao: "Outros", tipos: ["BL"], caminhos: ["freight.basic_value"], status: "pendente" },
  { key: "beneficiário", label: "BeneficiáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Beneficiário"], status: "pendente" },
  { key: "carteira", label: "Carteira", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Carteira"], status: "pendente" },
  { key: "freight_clauses[]_clause", label: "Clause", secao: "Outros", tipos: ["BL"], caminhos: ["freight.clauses[].clause"], status: "pendente" },
  { key: "cliente", label: "Cliente", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Cliente"], status: "pendente" },
  { key: "cnpj do beneficiário", label: "CNPJ Do BeneficiáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["CNPJ do Beneficiário"], status: "pendente" },
  { key: "cnpj do cliente", label: "CNPJ Do Cliente", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["CNPJ do Cliente"], status: "pendente" },
  { key: "freight_currency", label: "Currency", secao: "Outros", tipos: ["BL"], caminhos: ["freight.currency"], status: "pendente" },
  { key: "declaredvalues_customsvalue", label: "Customs Value", secao: "Outros", tipos: ["AWB"], caminhos: ["declaredValues.customsValue"], status: "pendente" },
  { key: "data de vencimento", label: "Data De Vencimento", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Data de Vencimento"], status: "pendente" },
  { key: "descontos", label: "Descontos", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Descontos"], status: "pendente" },
  { key: "itens[]_destinatário", label: "DestinatáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Destinatário"], status: "pendente" },
  { key: "route_destinationairport", label: "Destination Airport", secao: "Outros", tipos: ["AWB"], caminhos: ["route.destinationAirport"], status: "pendente" },
  { key: "values_discountsoradditions", label: "Discounts Or Additions", secao: "Outros", tipos: ["INVOICE"], caminhos: ["values.discountsOrAdditions"], status: "pendente" },
  { key: "emissão", label: "EmissãO", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Emissão"], status: "pendente" },
  { key: "itens[]_emissão", label: "EmissãO", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Emissão"], status: "pendente" },
  { key: "endereço do beneficiário", label: "EndereçO Do BeneficiáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Endereço do Beneficiário"], status: "pendente" },
  { key: "endereço do cliente", label: "EndereçO Do Cliente", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Endereço do Cliente"], status: "pendente" },
  { key: "fatura", label: "Fatura", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Fatura"], status: "pendente" },
  { key: "itens[]_filial", label: "Filial", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Filial"], status: "pendente" },
  { key: "awbinfo_flight_flightdate", label: "Flight Date", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.flight.flightDate"], status: "pendente" },
  { key: "awbinfo_flight_flightnumber", label: "Flight Number", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.flight.flightNumber"], status: "pendente" },
  { key: "handlinginformation", label: "Handling Information", secao: "Outros", tipos: ["AWB"], caminhos: ["handlingInformation"], status: "pendente" },
  { key: "woodpackaging_haswood", label: "Has Wood", secao: "Outros", tipos: ["BL"], caminhos: ["woodPackaging.hasWood"], status: "pendente" },
  { key: "awbinfo_hawbnumber", label: "Hawb Number", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.hawbNumber"], status: "pendente" },
  { key: "cargoagent_iatacode", label: "Iata Code", secao: "Outros", tipos: ["AWB"], caminhos: ["cargoAgent.iataCode"], status: "pendente" },
  { key: "instruções de responsabilidade do beneficiário", label: "InstruçõEs De Responsabilidade Do BeneficiáRio", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Instruções de Responsabilidade do Beneficiário"], status: "pendente" },
  { key: "woodpackaging_istreatedcertified", label: "Is Treated Certified", secao: "Outros", tipos: ["BL"], caminhos: ["woodPackaging.isTreatedCertified"], status: "pendente" },
  { key: "items_quantity", label: "Items Quantity", secao: "Outros", tipos: ["INVOICE"], caminhos: ["items_quantity"], status: "pendente" },
  { key: "linha digitável", label: "Linha DigitáVel", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Linha Digitável"], status: "pendente" },
  { key: "awbinfo_mawbnumber", label: "Mawb Number", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.mawbNumber"], status: "pendente" },
  { key: "freight_additional_charges[]_moeda", label: "Moeda", secao: "Outros", tipos: ["BL"], caminhos: ["freight.additional_charges[].Moeda"], status: "pendente" },
  { key: "moeda", label: "Moeda", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Moeda"], status: "pendente" },
  { key: "nome_outros", label: "Nome (Outros)", secao: "Outros", tipos: ["AWB"], caminhos: ["cargoAgent.name"], status: "mapeado" },
  { key: "freight_additional_charges[]_nome da taxa", label: "Nome Da Taxa", secao: "Outros", tipos: ["BL"], caminhos: ["freight.additional_charges[].Nome da Taxa"], status: "pendente" },
  { key: "nosso número", label: "Nosso NúMero", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Nosso Número"], status: "pendente" },
  { key: "itens[]_número", label: "NúMero", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Número"], status: "pendente" },
  { key: "itens[]_número controle", label: "NúMero Controle", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Número Controle"], status: "pendente" },
  { key: "número do documento", label: "NúMero Do Documento", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Número do Documento"], status: "pendente" },
  { key: "itens[]_número nf", label: "NúMero NF", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Número NF"], status: "pendente" },
  { key: "route_originairport", label: "Origin Airport", secao: "Outros", tipos: ["AWB"], caminhos: ["route.originAirport"], status: "pendente" },
  { key: "values_othercharges", label: "Other Charges", secao: "Outros", tipos: ["INVOICE"], caminhos: ["values.otherCharges"], status: "pendente" },
  { key: "parcela", label: "Parcela", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Parcela"], status: "pendente" },
  { key: "freight_payment_terms", label: "Payment Terms", secao: "Outros", tipos: ["BL"], caminhos: ["freight.payment_terms"], status: "pendente" },
  { key: "itens[]_peso", label: "Peso", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Peso"], status: "pendente" },
  { key: "itens[]_remetente", label: "Remetente", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Remetente"], status: "pendente" },
  { key: "itens[]_série", label: "SéRie", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Série"], status: "pendente" },
  { key: "awbinfo_shippedonboarddate", label: "Shipped On Board Date", secao: "Outros", tipos: ["AWB"], caminhos: ["awbInfo.shippedOnBoardDate"], status: "pendente" },
  { key: "itens[]_tipo", label: "Tipo", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Tipo"], status: "pendente" },
  { key: "values_totaldocumentvalue", label: "Total Document Value", secao: "Outros", tipos: ["INVOICE"], caminhos: ["values.totalDocumentValue"], status: "pendente" },
  { key: "freight_total_value", label: "Total Value", secao: "Outros", tipos: ["BL"], caminhos: ["freight.total_value"], status: "pendente" },
  { key: "declaredvalues_transportvalue", label: "Transport Value", secao: "Outros", tipos: ["AWB"], caminhos: ["declaredValues.transportValue"], status: "pendente" },
  { key: "freight_additional_charges[]_valor", label: "Valor", secao: "Outros", tipos: ["BL"], caminhos: ["freight.additional_charges[].Valor"], status: "pendente" },
  { key: "itens[]_valor", label: "Valor", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Valor"], status: "pendente" },
  { key: "valor bruto", label: "Valor Bruto", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Valor Bruto"], status: "pendente" },
  { key: "valor da parcela", label: "Valor Da Parcela", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Valor da Parcela"], status: "pendente" },
  { key: "valor líquido", label: "Valor LíQuido", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["Valor Líquido"], status: "pendente" },
  { key: "itens[]_valor nf", label: "Valor NF", secao: "Outros", tipos: ["FINANCIAL_DOCUMENT"], caminhos: ["itens[].Valor NF"], status: "pendente" },
  { key: "woodpackaging_wooddescription", label: "Wood Description", secao: "Outros", tipos: ["BL"], caminhos: ["woodPackaging.woodDescription"], status: "pendente" },
  { key: "condicao_pagamento_pagamento", label: "Condição de pagamento (Pagamento)", secao: "Pagamento", tipos: ["INVOICE"], caminhos: ["payment.terms"], status: "mapeado" },
  { key: "metodo_pagamento_pagamento", label: "Método de pagamento (Pagamento)", secao: "Pagamento", tipos: ["INVOICE"], caminhos: ["payment.method"], status: "mapeado" },
  { key: "peso_bruto_total_resumo_volumes", label: "Peso bruto total (Resumo volumes)", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.totalGrossWeight"], status: "mapeado" },
  { key: "peso_liquido_total_resumo_volumes", label: "Peso líquido total (Resumo volumes)", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.totalNetWeight"], status: "mapeado" },
  { key: "packagesummary_totalcubicmeasurement", label: "Total Cubic Measurement", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.totalCubicMeasurement"], status: "pendente" },
  { key: "total_volumes_resumo_volumes", label: "Total de volumes (Resumo volumes)", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.totalPackages"], status: "mapeado" },
  { key: "packagesummary_totaltareweight", label: "Total Tare Weight", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.totalTareWeight"], status: "pendente" },
  { key: "unidade_comercial_resumo_volumes", label: "Unidade comercial (Resumo volumes)", secao: "Resumo volumes", tipos: ["INVOICE", "PACKING_LIST"], caminhos: ["packageSummary.commercialUnit"], status: "mapeado" },
  { key: "charges_internationalfreight_agentothercharges", label: "Agent Other Charges", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.agentOtherCharges"], status: "pendente" },
  { key: "charges_internationalfreight_airlineothercharges", label: "Airline Other Charges", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.airlineOtherCharges"], status: "pendente" },
  { key: "charges_internationalfreight_basicfreightamount", label: "Basic Freight Amount", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.basicFreightAmount"], status: "pendente" },
  { key: "charges_internationalfreight_currency", label: "Currency", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.currency"], status: "pendente" },
  { key: "charges_internationalfreight_currencyconversionrates", label: "Currency Conversion Rates", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.currencyConversionRates"], status: "pendente" },
  { key: "charges_internationalfreight_declaredvaluefee", label: "Declared Value Fee", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.declaredValueFee"], status: "pendente" },
  { key: "charges_internationalfreight_destinationcharges", label: "Destination Charges", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.destinationCharges"], status: "pendente" },
  { key: "charges_internationalfreight_freighttax", label: "Freight Tax", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.freightTax"], status: "pendente" },
  { key: "charges_internationalfreight_paymenttype", label: "Payment Type", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.paymentType"], status: "pendente" },
  { key: "charges_internationalfreight_rate", label: "Rate", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.rate"], status: "pendente" },
  { key: "charges_internationalfreight_totalamounttocollect", label: "Total Amount To Collect", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.totalAmountToCollect"], status: "pendente" },
  { key: "charges_internationalfreight_totalfreightamount", label: "Total Freight Amount", secao: "Taxas", tipos: ["AWB"], caminhos: ["charges.internationalFreight.totalFreightAmount"], status: "pendente" },
  { key: "nome_transportadora", label: "Nome (Transportadora)", secao: "Transportadora", tipos: ["BL"], caminhos: ["carrier.name"], status: "mapeado" },
]

export const TIPOS_DOCUMENTO_SMART_READ: string[] = ["AWB", "BL", "FINANCIAL_DOCUMENT", "INVOICE", "PACKING_LIST"]
