import type { Empresa as PrismaEmpresa } from '../../../generated/index.js'

export function toEmpresaDto(e: PrismaEmpresa): Record<string, unknown> {
  return {
    id_empresa: e.id_empresa,
    id_organizacao: e.id_organizacao_empresa,
    nome_empresa: e.nome_empresa,
    cnpj_empresa: e.cnpj_empresa,
    tin_empresa: e.tin_empresa,
    pais_empresa: e.pais_empresa,
    estado_provincia_empresa: e.estado_provincia_empresa,
    cidade_empresa: e.cidade_empresa,
    endereco_empresa: e.endereco_empresa,
    cep_zipcode_empresa: e.cep_zipcode_empresa,
    email_principal_empresa: e.email_principal_empresa,
    telefone_principal_empresa: e.telefone_principal_empresa,
    whatsapp_principal_empresa: e.whatsapp_principal_empresa,
    pode_ser_importador_empresa: e.pode_ser_importador_empresa,
    pode_ser_exportador_empresa: e.pode_ser_exportador_empresa,
    pode_ser_fabricante_empresa: e.pode_ser_fabricante_empresa,
    pode_ser_agente_empresa: e.pode_ser_agente_empresa,
    pode_ser_despachante_empresa: e.pode_ser_despachante_empresa,
    pode_ser_armador_empresa: e.pode_ser_armador_empresa,
    pode_ser_cia_aerea_empresa: e.pode_ser_cia_aerea_empresa,
    pode_ser_transportadora_rodoviaria_nacional_empresa: e.pode_ser_transportadora_rodoviaria_nacional_empresa,
    pode_ser_transportadora_rodoviaria_internacional_empresa: e.pode_ser_transportadora_rodoviaria_internacional_empresa,
    pode_ser_armazem_alfandegado_empresa: e.pode_ser_armazem_alfandegado_empresa,
    pode_ser_armazem_nacional_empresa: e.pode_ser_armazem_nacional_empresa,
    pode_ser_banco_empresa: e.pode_ser_banco_empresa,
    pode_ser_seguradora_internacional_empresa: e.pode_ser_seguradora_internacional_empresa,
    pode_ser_seguradora_corretora_cambio_empresa: e.pode_ser_seguradora_corretora_cambio_empresa,
    ativo_empresa: e.ativo_empresa,
    criado_em_empresa: e.criado_em_empresa.toISOString(),
    atualizado_em_empresa: e.atualizado_em_empresa.toISOString(),
  }
}

/** Compat Pedido legado — shape fornecedor a partir de Empresa. */
export function empresaParaFornecedorCompatDto(e: PrismaEmpresa): Record<string, unknown> {
  return {
    id_fornecedor: e.id_empresa,
    id_organizacao: e.id_organizacao_empresa,
    nome_fornecedor: e.nome_empresa,
    cnpj_fornecedor: e.cnpj_empresa,
    tin_fornecedor: e.tin_empresa,
    pais_fornecedor: e.pais_empresa,
    estado_provincia_fornecedor: e.estado_provincia_empresa,
    cidade_fornecedor: e.cidade_empresa,
    endereco_fornecedor: e.endereco_empresa,
    cep_zipcode_fornecedor: e.cep_zipcode_empresa,
    email_principal_fornecedor: e.email_principal_empresa,
    telefone_principal_fornecedor: e.telefone_principal_empresa,
    whatsapp_principal_fornecedor: e.whatsapp_principal_empresa,
    pode_ser_importador_fornecedor: e.pode_ser_importador_empresa,
    pode_ser_exportador_fornecedor: e.pode_ser_exportador_empresa,
    pode_ser_fabricante_fornecedor: e.pode_ser_fabricante_empresa,
    pode_ser_agente_fornecedor: e.pode_ser_agente_empresa,
    pode_ser_despachante_fornecedor: e.pode_ser_despachante_empresa,
    pode_ser_armador_fornecedor: e.pode_ser_armador_empresa,
    pode_ser_cia_aerea_fornecedor: e.pode_ser_cia_aerea_empresa,
    pode_ser_transportadora_rodoviaria_nacional_fornecedor: e.pode_ser_transportadora_rodoviaria_nacional_empresa,
    pode_ser_transportadora_rodoviaria_internacional_fornecedor: e.pode_ser_transportadora_rodoviaria_internacional_empresa,
    pode_ser_armazem_alfandegado_fornecedor: e.pode_ser_armazem_alfandegado_empresa,
    pode_ser_armazem_nacional_fornecedor: e.pode_ser_armazem_nacional_empresa,
    pode_ser_banco_fornecedor: e.pode_ser_banco_empresa,
    pode_ser_seguradora_internacional_fornecedor: e.pode_ser_seguradora_internacional_empresa,
    pode_ser_seguradora_corretora_cambio_fornecedor: e.pode_ser_seguradora_corretora_cambio_empresa,
    ativo_fornecedor: e.ativo_empresa,
    criado_em_fornecedor: e.criado_em_empresa.toISOString(),
    atualizado_em_fornecedor: e.atualizado_em_empresa.toISOString(),
  }
}
