/**
 * dashboardCatalog.ts — Catálogo de campos do Dashboard Pedido
 *
 * Cada campo é um CatalogField enriquecido com:
 * - semanticType: semântica para o motor de sugestão
 * - domain: entidade de origem (pedido | item)
 * - complementaryFields: campos que fazem sentido combinados
 * - chartTypes: visualizações compatíveis
 * - dimension?: agrupamento para futura rota GROUP BY (Option B)
 */

import type { EnrichedCatalogField } from '@nucleo/dashboard'

export type { EnrichedCatalogField } from '@nucleo/dashboard'

export const DASHBOARD_CATALOG: EnrichedCatalogField[] = [

  // ── Pedido — Contagens ──────────────────────────────────────────────────────
  {
    key: 'total_pedidos',
    label: 'Total de Pedidos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['pedidos_atrasados', 'pedidos_abertos', 'pedidos_em_andamento'],
  },
  {
    key: 'pedidos_abertos',
    label: 'Pedidos Abertos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_em_andamento', 'pedidos_atrasados'],
    dimension: 'status_pedido',
  },
  {
    key: 'pedidos_em_andamento',
    label: 'Em Andamento',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos', 'pedidos_atrasados'],
    dimension: 'status_pedido',
  },
  {
    key: 'pedidos_atrasados',
    label: 'Pedidos Atrasados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
  },
  {
    key: 'pedidos_consolidados',
    label: 'Consolidados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
  },
  {
    key: 'pedidos_cancelados',
    label: 'Cancelados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos'],
    dimension: 'status_pedido',
  },
  {
    key: 'pedidos_draft',
    label: 'Rascunhos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
  },

  // ── Pedido — Financeiro ─────────────────────────────────────────────────────
  {
    key: 'valor_total',
    label: 'Valor Total dos Pedidos',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['cobertura_pendente', 'valor_itens_total', 'total_pedidos'],
  },
  {
    key: 'valor_total_brl',
    label: 'Total Pedidos — BRL',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'cobertura_pendente', 'total_pedidos'],
  },
  {
    key: 'cobertura_pendente',
    label: 'Cobertura Pendente',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'valor_itens_total'],
    dimension: 'cobertura_status',
  },
  {
    key: 'valor_itens_total',
    label: 'Valor Total dos Itens',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'cobertura_pendente'],
  },

  // ── Pedido — Quantidade ────────────────────────────────────────────────────
  {
    key: 'qtd_total',
    label: 'Quantidade Total',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'sum_qty',
    domain: 'pedido',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total'],
  },

  // ── Item — Quantidades ──────────────────────────────────────────────────────
  {
    key: 'itens_prontos',
    label: 'Itens Prontos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION'],
    semanticType: 'sum_qty',
    domain: 'item',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total', 'qtd_transferida_total'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_atual_total',
    label: 'Qtd. Atual (Itens)',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION'],
    semanticType: 'sum_qty',
    domain: 'item',
    complementaryFields: ['qtd_inicial_total', 'itens_prontos', 'qtd_transferida_total'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_transferida_total',
    label: 'Qtd. Transferida',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION'],
    semanticType: 'sum_qty',
    domain: 'item',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total', 'itens_prontos'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_inicial_total',
    label: 'Qtd. Inicial (Itens)',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'sum_qty',
    domain: 'item',
    complementaryFields: ['qtd_atual_total', 'itens_prontos', 'qtd_transferida_total'],
  },
]

export const CATALOG_BY_KEY = Object.fromEntries(
  DASHBOARD_CATALOG.map(f => [f.key, f]),
)
