/**
 * mockData.ts — Dados mock para desenvolvimento sem backend
 *
 * Usado quando pedidoVirtualApi.listar falha em import.meta.env.DEV.
 * Fórmula sagrada: quantidade_inicial = quantidade_atual + quantidade_transferida + quantidade_cancelada
 */

import type { PedidosListResponse } from './types'

export const MOCK_PEDIDOS_RESPONSE: PedidosListResponse = {
  data: [
    {
      id: 'pedi_id_0000001/26',
      tenant_id: 'tenant-demo',
      company_id: 'company-demo',
      tipo_operacao: 'importacao',
      numero_pedido: 'PO-2026/001',
      status: 'aberto',
      importacao_exportador_id: 'exp-001',
      exportacao_importador_id: null,
      exportador_nome: 'Shenzhen Electronics Co.',
      fabricante_nome: 'Shenzhen Electronics Co.',
      incoterm: 'FOB',
      moeda_pedido: 'USD',
      valor_total_pedido: 45000,
      casas_decimais_total_pedido: 2,
      quantidade_total_pedido: 1500,
      casas_decimais_quantidade_total_pedido: 2,
      unidade_comercializada_pedido: 'UN',
      quantidade_inicial_total: 1700,
      quantidade_transferida_total: 310,
      cobertura_cambial: 'com_cobertura',
      condicao_pagamento: '30% Antecipado',
      data_emissao_pedido: '2026-03-15',
      numero_proforma: 'PRO-2026/001',
      numero_invoice: 'INV-2026/001',
      referencia_importador: 'REF-IMP-001',
      referencia_exportador: 'EXP-REF-001',
      referencia_fabricante: 'FAB-REF-001',
      itens: [
        {
          id: 'item-001-a',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000001/26',
          sequencia_item: 1,
          part_number: 'PCB-MCU-32F',
          ncm: '85423100',
          descricao: 'Microcontrolador 32-bit STM32F405RGT6',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 1000,
          quantidade_atual: 700,
          quantidade_pronta: 300,
          quantidade_transferida: 250,
          quantidade_cancelada: 50,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 15000,
          valor_unitario: 15.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-001-b',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000001/26',
          sequencia_item: 2,
          part_number: 'CAP-100UF-25V',
          ncm: '85321000',
          descricao: 'Capacitor Eletrolítico 100uF 25V',
          unidade_comercializada_item: 'PC',
          quantidade_inicial: 500,
          quantidade_atual: 500,
          quantidade_pronta: 0,
          quantidade_transferida: 0,
          quantidade_cancelada: 0,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 5000,
          valor_unitario: 10.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-001-c',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000001/26',
          sequencia_item: 3,
          part_number: 'PWR-MOSFET-N',
          ncm: '85413000',
          descricao: 'MOSFET Canal-N 60V 30A IRF3205',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 200,
          quantidade_atual: 120,
          quantidade_pronta: 80,
          quantidade_transferida: 60,
          quantidade_cancelada: 20,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 3600,
          valor_unitario: 18.00,
          casas_decimais_total_item: 2,
        },
      ],
      created_at: '2026-03-15T10:00:00Z',
      updated_at: '2026-03-15T10:00:00Z',
    },
    {
      id: 'pedi_id_0000002/26',
      tenant_id: 'tenant-demo',
      company_id: 'company-demo',
      tipo_operacao: 'importacao',
      numero_pedido: 'PO-2026/002',
      status: 'draft',
      importacao_exportador_id: 'exp-002',
      exportacao_importador_id: null,
      exportador_nome: 'Ningbo Hardware Supplies Ltd.',
      fabricante_nome: 'Ningbo Hardware Supplies Ltd.',
      incoterm: 'CIF',
      moeda_pedido: 'USD',
      valor_total_pedido: 12500,
      casas_decimais_total_pedido: 2,
      quantidade_total_pedido: 500,
      casas_decimais_quantidade_total_pedido: 2,
      unidade_comercializada_pedido: 'KG',
      quantidade_inicial_total: 500,
      quantidade_transferida_total: 0,
      cobertura_cambial: 'sem_cobertura',
      condicao_pagamento: '100% Antecipado',
      data_emissao_pedido: '2026-03-22',
      numero_proforma: 'PRO-2026/002',
      numero_invoice: null,
      referencia_importador: 'REF-IMP-002',
      referencia_exportador: null,
      referencia_fabricante: null,
      itens: [
        {
          id: 'item-002-a',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000002/26',
          sequencia_item: 1,
          part_number: 'AX-BOLT-M8-50',
          ncm: '73181500',
          descricao: 'Parafuso Sextavado M8x50mm Aço Inox',
          unidade_comercializada_item: 'KG',
          quantidade_inicial: 300,
          quantidade_atual: 300,
          quantidade_pronta: 0,
          quantidade_transferida: 0,
          quantidade_cancelada: 0,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 7500,
          valor_unitario: 25.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-002-b',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000002/26',
          sequencia_item: 2,
          part_number: 'AX-NUT-M8',
          ncm: '73181600',
          descricao: 'Porca Sextavada M8 Aço Inox',
          unidade_comercializada_item: 'KG',
          quantidade_inicial: 200,
          quantidade_atual: 200,
          quantidade_pronta: 0,
          quantidade_transferida: 0,
          quantidade_cancelada: 0,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 5000,
          valor_unitario: 25.00,
          casas_decimais_total_item: 2,
        },
      ],
      created_at: '2026-03-22T14:30:00Z',
      updated_at: '2026-03-22T14:30:00Z',
    },
    {
      id: 'pedi_id_0000003/26',
      tenant_id: 'tenant-demo',
      company_id: 'company-demo',
      tipo_operacao: 'importacao',
      numero_pedido: 'PO-2026/003',
      status: 'transferencia',
      importacao_exportador_id: 'exp-003',
      exportacao_importador_id: null,
      exportador_nome: 'Guangdong Plastics Factory',
      fabricante_nome: 'Guangdong Plastics Factory',
      incoterm: 'EXW',
      moeda_pedido: 'USD',
      valor_total_pedido: 28000,
      casas_decimais_total_pedido: 2,
      quantidade_total_pedido: 4000,
      casas_decimais_quantidade_total_pedido: 2,
      unidade_comercializada_pedido: 'UN',
      quantidade_inicial_total: 4000,
      quantidade_transferida_total: 2000,
      cobertura_cambial: 'com_cobertura',
      condicao_pagamento: '50% Antecipado / 50% BL',
      data_emissao_pedido: '2026-02-28',
      numero_proforma: 'PRO-2026/003',
      numero_invoice: 'INV-2026/003',
      referencia_importador: 'REF-IMP-003',
      referencia_exportador: 'GDF-2026-0312',
      referencia_fabricante: 'GDF-FAB-0312',
      itens: [
        {
          id: 'item-003-a',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000003/26',
          sequencia_item: 1,
          part_number: 'INJ-CASE-A200',
          ncm: '39269090',
          descricao: 'Carcaça Plástica Injetada Modelo A200',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 2000,
          quantidade_atual: 800,
          quantidade_pronta: 1200,
          quantidade_transferida: 1000,
          quantidade_cancelada: 200,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 14000,
          valor_unitario: 7.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-003-b',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000003/26',
          sequencia_item: 2,
          part_number: 'INJ-COVER-A200',
          ncm: '39269090',
          descricao: 'Tampa Plástica Injetada Modelo A200',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 2000,
          quantidade_atual: 900,
          quantidade_pronta: 1100,
          quantidade_transferida: 1000,
          quantidade_cancelada: 100,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 14000,
          valor_unitario: 7.00,
          casas_decimais_total_item: 2,
        },
      ],
      created_at: '2026-02-28T09:00:00Z',
      updated_at: '2026-03-20T16:45:00Z',
    },
    {
      id: 'pedi_id_0000004/26',
      tenant_id: 'tenant-demo',
      company_id: 'company-demo',
      tipo_operacao: 'exportacao',
      numero_pedido: 'SO-2026/001',
      status: 'consolidado',
      importacao_exportador_id: null,
      exportacao_importador_id: 'imp-004',
      exportador_nome: 'Gravity Soluções Ltda.',
      fabricante_nome: 'Gravity Soluções Ltda.',
      incoterm: 'FOB',
      moeda_pedido: 'USD',
      valor_total_pedido: 85000,
      casas_decimais_total_pedido: 2,
      quantidade_total_pedido: 2500,
      casas_decimais_quantidade_total_pedido: 2,
      unidade_comercializada_pedido: 'UN',
      quantidade_inicial_total: 2500,
      quantidade_transferida_total: 2500,
      cobertura_cambial: 'com_cobertura',
      condicao_pagamento: 'L/C à Vista',
      data_emissao_pedido: '2026-01-10',
      numero_proforma: 'PRO-SO-2026/001',
      numero_invoice: 'INV-SO-2026/001',
      referencia_importador: 'ARG-REF-2026-001',
      referencia_exportador: 'GRV-SO-001',
      referencia_fabricante: 'GRV-FAB-001',
      itens: [
        {
          id: 'item-004-a',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000004/26',
          sequencia_item: 1,
          part_number: 'SFT-LICENSE-ENT',
          ncm: '85234990',
          descricao: 'Licença de Software Enterprise — Pacote Anual',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 1500,
          quantidade_atual: 0,
          quantidade_pronta: 1500,
          quantidade_transferida: 1500,
          quantidade_cancelada: 0,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 52500,
          valor_unitario: 35.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-004-b',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000004/26',
          sequencia_item: 2,
          part_number: 'SVC-IMPL-DIAS',
          ncm: '85234990',
          descricao: 'Serviço de Implementação — Diárias',
          unidade_comercializada_item: 'DIA',
          quantidade_inicial: 1000,
          quantidade_atual: 0,
          quantidade_pronta: 1000,
          quantidade_transferida: 1000,
          quantidade_cancelada: 0,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 32500,
          valor_unitario: 32.50,
          casas_decimais_total_item: 2,
        },
      ],
      created_at: '2026-01-10T08:00:00Z',
      updated_at: '2026-03-05T11:20:00Z',
    },
    {
      id: 'pedi_id_0000005/26',
      tenant_id: 'tenant-demo',
      company_id: 'company-demo',
      tipo_operacao: 'importacao',
      numero_pedido: 'PO-2026/004',
      status: 'cancelado',
      importacao_exportador_id: 'exp-005',
      exportacao_importador_id: null,
      exportador_nome: 'Taiwan Semiconductor Supply',
      fabricante_nome: 'TSMC Authorized Distributor',
      incoterm: 'CIF',
      moeda_pedido: 'USD',
      valor_total_pedido: 9800,
      casas_decimais_total_pedido: 2,
      quantidade_total_pedido: 200,
      casas_decimais_quantidade_total_pedido: 2,
      unidade_comercializada_pedido: 'UN',
      quantidade_inicial_total: 200,
      quantidade_transferida_total: 0,
      cobertura_cambial: 'sem_cobertura',
      condicao_pagamento: '100% Antecipado',
      data_emissao_pedido: '2026-02-05',
      numero_proforma: 'PRO-2026/004',
      numero_invoice: null,
      referencia_importador: 'REF-IMP-004',
      referencia_exportador: 'TSS-2026-0205',
      referencia_fabricante: null,
      itens: [
        {
          id: 'item-005-a',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000005/26',
          sequencia_item: 1,
          part_number: 'IC-FPGA-XC7A35T',
          ncm: '85423100',
          descricao: 'FPGA Xilinx Artix-7 XC7A35T-1CSG324C',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 150,
          quantidade_atual: 0,
          quantidade_pronta: 0,
          quantidade_transferida: 0,
          quantidade_cancelada: 150,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 7350,
          valor_unitario: 49.00,
          casas_decimais_total_item: 2,
        },
        {
          id: 'item-005-b',
          tenant_id: 'tenant-demo',
          company_id: 'company-demo',
          pedido_id: 'pedi_id_0000005/26',
          sequencia_item: 2,
          part_number: 'IC-DDR4-4GB',
          ncm: '85423100',
          descricao: 'Módulo DDR4 4GB SO-DIMM 2666MHz',
          unidade_comercializada_item: 'UN',
          quantidade_inicial: 50,
          quantidade_atual: 0,
          quantidade_pronta: 0,
          quantidade_transferida: 0,
          quantidade_cancelada: 50,
          casas_decimais_quantidade: 2,
          moeda_item: 'USD',
          valor_item: 2450,
          valor_unitario: 49.00,
          casas_decimais_total_item: 2,
        },
      ],
      created_at: '2026-02-05T13:00:00Z',
      updated_at: '2026-02-18T10:30:00Z',
    },
  ],
  nextCursor: null,
  total: 5,
  hasMore: false,
}
