import type { EnrichedCatalogField } from '@nucleo/dashboard'

/** Catálogo estático PT-BR para o construtor de widgets do simulador */
export const CATALOGO_DASHBOARD_SIMULADOR_PEDIDO: EnrichedCatalogField[] = [
  {
    key: 'total_pedidos',
    label: 'Total de Pedidos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['pedidos_atrasados', 'pedidos_abertos', 'pedidos_em_andamento'],
  },
  {
    key: 'pedidos_abertos',
    label: 'Pedidos Abertos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_em_andamento', 'pedidos_atrasados'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_em_andamento',
    label: 'Em Andamento',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos', 'pedidos_atrasados'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_atrasados',
    label: 'Pedidos Atrasados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_consolidados',
    label: 'Consolidados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_cancelados',
    label: 'Cancelados',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_rascunho',
    label: 'Rascunhos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
    dimension: 'status_pedido',
    dimensionLabel: 'Status dos Pedidos',
  },
  {
    key: 'pedidos_sem_exportador',
    label: 'Sem Exportador',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['total_pedidos', 'pedidos_abertos'],
  },
  {
    key: 'pedidos_importacao',
    label: 'Importação',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'DONUT', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['pedidos_exportacao', 'total_pedidos'],
    dimension: 'tipo_operacao',
    dimensionLabel: 'Tipo de Operação',
  },
  {
    key: 'pedidos_exportacao',
    label: 'Exportação',
    productId: 'pedido',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'DONUT', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'count',
    domain: 'pedido',
    complementaryFields: ['pedidos_importacao', 'total_pedidos'],
    dimension: 'tipo_operacao',
    dimensionLabel: 'Tipo de Operação',
  },
  {
    key: 'valor_total',
    label: 'Valor Total dos Pedidos',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['cobertura_pendente', 'valor_itens_total', 'total_pedidos'],
  },
  {
    key: 'valor_total_brl',
    label: 'Exposição Cambial (BRL)',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'cobertura_pendente', 'total_pedidos'],
  },
  {
    key: 'cobertura_pendente',
    label: 'Cobertura Cambial a Contratar',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'DISTRIBUTION', 'BAR', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'valor_itens_total'],
    dimension: 'cobertura_status',
  },
  {
    key: 'valor_itens_total',
    label: 'Valor dos Itens (FOB/CIF)',
    productId: 'pedido',
    type: 'currency',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'sum_currency',
    domain: 'pedido',
    complementaryFields: ['valor_total', 'cobertura_pendente'],
  },
  {
    key: 'qtd_total',
    label: 'Quantidade Total',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'sum_qty',
    domain: 'pedido',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total'],
  },
  {
    key: 'itens_prontos',
    label: 'Itens Prontos',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'sum_qty',
    domain: 'item',
    domainDisplayLabel: 'Itens',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total', 'qtd_transferida_total'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_pronta_total',
    label: 'Qtd. Pronta',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'sum_qty',
    domain: 'item',
    domainDisplayLabel: 'Itens',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total'],
  },
  {
    key: 'qtd_atual_total',
    label: 'Qtd. Atual (Itens)',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'sum_qty',
    domain: 'item',
    domainDisplayLabel: 'Itens',
    complementaryFields: ['qtd_inicial_total', 'itens_prontos', 'qtd_transferida_total'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_transferida_total',
    label: 'Qtd. Transferida',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'DISTRIBUTION', 'BAR_HORIZONTAL', 'AREA', 'DONUT'],
    semanticType: 'sum_qty',
    domain: 'item',
    domainDisplayLabel: 'Itens',
    complementaryFields: ['qtd_inicial_total', 'qtd_atual_total', 'itens_prontos'],
    dimension: 'status_item',
  },
  {
    key: 'qtd_inicial_total',
    label: 'Qtd. Inicial (Itens)',
    productId: 'pedido',
    type: 'number',
    aggregations: ['SUM'],
    permission: 'pedido.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR', 'BAR_HORIZONTAL', 'AREA'],
    semanticType: 'sum_qty',
    domain: 'item',
    domainDisplayLabel: 'Itens',
    complementaryFields: ['qtd_atual_total', 'itens_prontos', 'qtd_transferida_total'],
  },
]

export const CATALOGO_POR_CHAVE_SIMULADOR = Object.fromEntries(
  CATALOGO_DASHBOARD_SIMULADOR_PEDIDO.map(f => [f.key, f]),
)
