/** Textos PT — espelham `pedido.modal_transf` em nucleo-global/Utilidades/Localization/locales/pt.json */
export const TEXTOS_MODAL_TRANSFERIR_SIMULADOR_PEDIDO = {
  titulo: 'Transferir Pedido — {{numero}}',
  passo_cenario: 'Cenário',
  passo_item: 'Item',
  passo_destinos: 'Destinos',
  passo_preview: 'Preview',
  passo_confirmacao: 'Confirmação',
  cenario_tipo_label: 'Tipo de transferência',
  cenario_reducao_nome: 'Redução Simples',
  cenario_reducao_desc: 'Cancela a diferença — quantidade reduzida sem destino.',
  cenario_split_novo_nome: 'Split → Novo Pedido',
  cenario_split_novo_desc: 'Diferença vira um novo pedido com número definido.',
  cenario_split_exist_nome: 'Split → Pedido Existente',
  cenario_split_exist_desc: 'Diferença vai para um pedido que já existe.',
  badge_irreversivel: '· Irreversível',
  col_part_number: 'Part Number',
  col_descricao: 'Descrição do Item',
  col_saldo: 'Saldo',
  col_qty_transfer: 'Qtd',
  col_saldo_apos: 'Saldo Após',
  max_label: 'Máx:',
  destino_titulo: 'Destino',
  destino_id_label: 'Pedido destino',
  destino_id_placeholder: 'Selecione um pedido…',
  erro_carregar_pedidos: 'Falha ao carregar pedidos elegíveis. Tente novamente.',
  novo_pedido_label: 'Número do novo pedido',
  novo_pedido_placeholder: 'Ex: PO-2026/002',
  qty_a_transferir: 'Quantidade a transferir',
  alerta_reducao: 'A quantidade será cancelada sem destino. Esta operação não é reversível.',
  badge_novo: 'novo',
  badge_existente: 'existente',
  preview_origem: 'Pedido de Origem',
  preview_label_pedido: 'Pedido',
  preview_label_item: 'Item',
  preview_label_qtd_atual: 'Quantidade atual',
  preview_label_qtd_apos: 'Quantidade após',
  preview_ficara_zero: '(ficará zero)',
  preview_destino_titulo: 'Destino {{n}}',
  preview_numeracao: 'Item {{atual}} de {{total}}',
  preview_label_quantidade: 'Quantidade',
  aviso_tipos_titulo: 'Tipos de operação diferentes',
  aviso_tipos_msg:
    'O pedido de destino é de um tipo diferente (importação ↔ exportação). Confirme que deseja prosseguir mesmo assim.',
  confirm_tipos_divergentes: 'Confirmo que desejo transferir entre pedidos de tipos diferentes',
  passo5_reversivel: 'Revise o resumo acima antes de confirmar. Esta ação pode ser revertida posteriormente.',
  passo5_irreversivel: 'Revise o resumo acima antes de confirmar. Esta ação não pode ser revertida.',
  subtitulo: 'Mova itens entre pedidos da mesma organização',
  titulo_tooltip_pedidos: 'Pedidos selecionados',
  resultado_titulo: 'Transferência concluída com sucesso',
  secao_origem_resultado: 'Origem',
  secao_destino_resultado: 'Destino',
  sucesso_label_cenario: 'Cenário',
  sucesso_label_item: 'Item',
  sucesso_label_qtd: 'Quantidade processada',
  sucesso_label_novo_pedido: 'Novo pedido',
  sucesso_label_destino: 'Pedido(s) destino',
  sucesso_atualizado: '{{count}} pedido(s) atualizado(s)',
  calculando: 'Calculando impacto...',
  cancelar: 'Cancelar',
  voltar: 'Voltar',
  proximo: 'Próximo',
  revisar_confirmar: 'Revisar e Confirmar',
  confirmar: 'Confirmar Transferência',
  transferindo: 'Transferindo...',
  fechar: 'Fechar',
  aria_tabela_itens: 'Itens do pedido de origem',
  aria_qtd_transferir: 'Quantidade a transferir',
  passo1_label: 'Cenário',
  passo2_label: 'Quantidades',
  passo3_label: 'Destino',
  passo4_label: 'Revisão',
  passo5_label: 'Confirmação',
  col_pedido: 'Pedido',
  col_sequencia_item: 'Sequência do Item',
  aria_selecionar_item: 'Selecionar item {{item}}',
  aria_selecionar_todos: 'Selecionar todos os itens',
  carregando_pedidos: 'Carregando pedidos…',
  n_itens: '{{count}} itens',
  erro_calcular_preview: 'Não foi possível calcular o preview da transferência.',
  erro_confirmar: 'Não foi possível confirmar a transferência.',
} as const

export function interpolarTextoTransferir(
  template: string,
  vars: Record<string, string | number>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, chave: string) => String(vars[chave] ?? ''))
}
