/** Textos PT — espelham `pedido.modal_cons` (ModalPedidosConsolidar real) */
export const TEXTOS_MODAL_CONSOLIDAR_SIMULADOR_PEDIDO = {
  titulo: 'Consolidar {{count}} pedidos',
  subtitulo: 'Una pedidos compatíveis em um único pedido consolidado',
  passo1_label: 'Configurar',
  passo2_label: 'Comparar',
  passo3_label: 'Confirmar',
  passo_configurar: 'Configurar',
  passo_comparar: 'Comparar',
  passo_confirmar: 'Confirmar',
  secao_configuracao: 'Configuração',
  secao_preview: 'Prévia',
  numero_label: 'Número do pedido consolidado',
  numero_placeholder: 'Ex: PO-CONS-2026/001',
  numero_hint: 'Será o identificador único do novo pedido na organização.',
  fundir_part_number: 'Fundir itens com o mesmo Part Number (somar quantidades)',
  stat_pedidos: 'Pedidos',
  stat_itens: 'Itens',
  stat_pedidos_inteiros: 'Inteiros',
  stat_pedidos_parciais: 'Parciais',
  stat_divergencias: 'Divergências',
  stat_campos_iguais: 'Campos iguais',
  valor_total_consolidado: 'Valor total consolidado',
  conflito_titulo: 'Tipos de operação incompatíveis',
  conflito_msg: 'Não é possível consolidar pedidos de importação com exportação.',
  comparar_aviso_titulo: 'Pedidos diferentes, dados diferentes',
  comparar_aviso_desc:
    'Cada pedido de origem pode trazer Incoterm, moeda, exportador e outros campos distintos. Nos selects, o PO entre parênteses indica de qual pedido veio aquele valor — escolha o que prevalece no consolidado.',
  filtro_todos: 'Todos',
  filtro_divergentes: 'Divergentes',
  filtro_iguais: 'Iguais',
  filtro_vazios: 'Vazios',
  origem_label: 'Filtrar por pedido de origem',
  filtro_origem_placeholder: 'Todos os pedidos',
  todos_pedidos: 'Todos ({{count}})',
  badge_divergencia: '{{count}} origens',
  badge_igual: 'igual',
  badge_vazio: 'vazio',
  grupo_campos: '{{count}} campos',
  confirmacao_titulo: 'Pronto para consolidar',
  confirmacao_desc: '{{count}} pedidos serão unidos em {{numero}}. Os pedidos de origem saem da lista.',
  resumo_escolhas: '{{count}} divergência(s) resolvida(s)',
  pedidos_origem_arquivados: 'Pedidos de origem',
  chip_inteiro: '(inteiro)',
  chip_parcial: '({{count}} itens)',
  consolidar: 'Consolidar',
  consolidando: 'Consolidando...',
  proximo: 'Próximo',
  voltar: 'Voltar',
  cancelar: 'Cancelar',
  fechar: 'Fechar',
  carregando: 'Analisando pedidos...',
  resultado_banner: '{{numero}} criado com {{itens}} item(ns) a partir de {{pedidos}} pedido(s).',
  pedidos_origem_arquivados_resultado: 'Pedidos de origem arquivados',
  campos_divergentes_resolvidos: 'Divergências resolvidas',
  detalhe_inteiro: '{{count}} itens',
  detalhe_parcial: '{{count}} itens selecionados',
  item: '{{count}} item(ns)',
  pedido_fallback: 'Pedido {{id}}',
  erro_preview: 'Não foi possível gerar a prévia da consolidação.',
  erro_consolidar: 'Falha ao consolidar os pedidos.',
} as const

export function interpolarTextoConsolidar(
  template: string,
  vars: Record<string, string | number>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, chave: string) => String(vars[chave] ?? ''))
}
