/** Moedas — Portal Único Siscomex
 * Fonte: documentos-tecnicos/Tabela de Moedas Portal Único Siscomex.pdf
 */

export interface MoedaSiscomex {
  codigo: number
  descricao: string
  sigla: string
  nomeCampo: string
}

export const MOEDAS_SISCOMEX: MoedaSiscomex[] = [
  { codigo: 220, descricao: 'Dólar dos Estados Unidos',     sigla: 'USD', nomeCampo: 'USD - Dólar dos Estados Unidos' },
  { codigo: 978, descricao: 'Euro',                         sigla: 'EUR', nomeCampo: 'EUR - Euro' },
  { codigo: 790, descricao: 'Real (Brasil)',                sigla: 'BRL', nomeCampo: 'BRL - Real (Brasil)' },
  { codigo:   5, descricao: 'Afegane (Afeganistão)',        sigla: 'AFN', nomeCampo: 'AFN - Afegane' },
  { codigo:  15, descricao: 'Baht (Tailândia)',             sigla: 'THB', nomeCampo: 'THB - Baht' },
  { codigo:  20, descricao: 'Balboa (Panamá)',              sigla: 'PAB', nomeCampo: 'PAB - Balboa' },
  { codigo:  30, descricao: 'Boliviano (Bolívia)',          sigla: 'BOB', nomeCampo: 'BOB - Boliviano' },
  { codigo:  35, descricao: 'Cedi (Gana)',                  sigla: 'GHS', nomeCampo: 'GHS - Cedi' },
  { codigo:  40, descricao: 'Colón Costarriquenho',        sigla: 'CRC', nomeCampo: 'CRC - Colón Costarriquenho' },
  { codigo:  45, descricao: 'Colón Salvadorenho',          sigla: 'SVC', nomeCampo: 'SVC - Colón Salvadorenho' },
  { codigo:  55, descricao: 'Coroa Dinamarquesa',          sigla: 'DKK', nomeCampo: 'DKK - Coroa Dinamarquesa' },
  { codigo:  60, descricao: 'Coroa Islandesa',             sigla: 'ISK', nomeCampo: 'ISK - Coroa Islandesa' },
  { codigo:  65, descricao: 'Coroa Norueguesa',            sigla: 'NOK', nomeCampo: 'NOK - Coroa Norueguesa' },
  { codigo:  70, descricao: 'Coroa Sueca',                 sigla: 'SEK', nomeCampo: 'SEK - Coroa Sueca' },
  { codigo:  75, descricao: 'Coroa Tcheca',                sigla: 'CZK', nomeCampo: 'CZK - Coroa Tcheca' },
  { codigo:  90, descricao: 'Dalasi (Gâmbia)',             sigla: 'GMD', nomeCampo: 'GMD - Dalasi' },
  { codigo:  95, descricao: 'Dinar Argelino',              sigla: 'DZD', nomeCampo: 'DZD - Dinar Argelino' },
  { codigo: 100, descricao: 'Dinar Kuwaitiano',            sigla: 'KWD', nomeCampo: 'KWD - Dinar Kuwaitiano' },
  { codigo: 105, descricao: 'Dinar do Bahrein',            sigla: 'BHD', nomeCampo: 'BHD - Dinar do Bahrein' },
  { codigo: 115, descricao: 'Dinar Iraquiano',             sigla: 'IQD', nomeCampo: 'IQD - Dinar Iraquiano' },
  { codigo: 125, descricao: 'Dinar Jordaniano',            sigla: 'JOD', nomeCampo: 'JOD - Dinar Jordaniano' },
  { codigo: 130, descricao: 'Dinar Líbio',                 sigla: 'LYD', nomeCampo: 'LYD - Dinar Líbio' },
  { codigo: 135, descricao: 'Dinar Tunisiano',             sigla: 'TND', nomeCampo: 'TND - Dinar Tunisiano' },
  { codigo: 145, descricao: 'Dirham dos Emirados Árabes',  sigla: 'AED', nomeCampo: 'AED - Dirham' },
  { codigo: 150, descricao: 'Dólar Australiano',           sigla: 'AUD', nomeCampo: 'AUD - Dólar Australiano' },
  { codigo: 155, descricao: 'Dólar das Bahamas',           sigla: 'BSD', nomeCampo: 'BSD - Dólar das Bahamas' },
  { codigo: 160, descricao: 'Dólar das Bermudas',          sigla: 'BMD', nomeCampo: 'BMD - Dólar das Bermudas' },
  { codigo: 165, descricao: 'Dólar Canadense',             sigla: 'CAD', nomeCampo: 'CAD - Dólar Canadense' },
  { codigo: 170, descricao: 'Dólar da Guiana',             sigla: 'GYD', nomeCampo: 'GYD - Dólar da Guiana' },
  { codigo: 175, descricao: 'Dólar de Barbados',           sigla: 'BBD', nomeCampo: 'BBD - Dólar de Barbados' },
  { codigo: 185, descricao: 'Dólar de Brunei',             sigla: 'BND', nomeCampo: 'BND - Dólar de Brunei' },
  { codigo: 190, descricao: 'Dólar das Ilhas Cayman',      sigla: 'KYD', nomeCampo: 'KYD - Dólar das Ilhas Cayman' },
  { codigo: 195, descricao: 'Dólar de Cingapura',          sigla: 'SGD', nomeCampo: 'SGD - Dólar de Cingapura' },
  { codigo: 200, descricao: 'Dólar de Fiji',               sigla: 'FJD', nomeCampo: 'FJD - Dólar de Fiji' },
  { codigo: 205, descricao: 'Dólar de Hong Kong',          sigla: 'HKD', nomeCampo: 'HKD - Dólar de Hong Kong' },
  { codigo: 210, descricao: 'Dólar de Trinidad e Tobago',  sigla: 'TTD', nomeCampo: 'TTD - Dólar de Trinidad e Tobago' },
  { codigo: 215, descricao: 'Dólar do Caribe Oriental',    sigla: 'XCD', nomeCampo: 'XCD - Dólar do Caribe Oriental' },
  { codigo: 230, descricao: 'Dólar Jamaicano',             sigla: 'JMD', nomeCampo: 'JMD - Dólar Jamaicano' },
  { codigo: 235, descricao: 'Dólar Liberiano',             sigla: 'LRD', nomeCampo: 'LRD - Dólar Liberiano' },
  { codigo: 245, descricao: 'Dólar da Nova Zelândia',      sigla: 'NZD', nomeCampo: 'NZD - Dólar da Nova Zelândia' },
  { codigo: 255, descricao: 'Dólar do Suriname',           sigla: 'SRD', nomeCampo: 'SRD - Dólar do Suriname' },
  { codigo: 260, descricao: 'Dongue (Vietnã)',              sigla: 'VND', nomeCampo: 'VND - Dongue' },
  { codigo: 275, descricao: 'Dram Armênio',                sigla: 'AMD', nomeCampo: 'AMD - Dram Armênio' },
  { codigo: 345, descricao: 'Forint (Hungria)',             sigla: 'HUF', nomeCampo: 'HUF - Forint' },
  { codigo: 365, descricao: 'Franco do Burundi',           sigla: 'BIF', nomeCampo: 'BIF - Franco do Burundi' },
  { codigo: 370, descricao: 'Franco CFA Central',          sigla: 'XAF', nomeCampo: 'XAF - Franco CFA Central' },
  { codigo: 372, descricao: 'Franco CFA Ocidental',        sigla: 'XOF', nomeCampo: 'XOF - Franco CFA Ocidental' },
  { codigo: 380, descricao: 'Franco CFP',                  sigla: 'XPF', nomeCampo: 'XPF - Franco CFP' },
  { codigo: 420, descricao: 'Franco Ruandês',              sigla: 'RWF', nomeCampo: 'RWF - Franco Ruandês' },
  { codigo: 425, descricao: 'Franco Suíço',                sigla: 'CHF', nomeCampo: 'CHF - Franco Suíço' },
  { codigo: 440, descricao: 'Gourde (Haiti)',               sigla: 'HTG', nomeCampo: 'HTG - Gourde' },
  { codigo: 450, descricao: 'Guarani (Paraguai)',           sigla: 'PYG', nomeCampo: 'PYG - Guarani' },
  { codigo: 470, descricao: 'Iene (Japão)',                 sigla: 'JPY', nomeCampo: 'JPY - Iene (Japão)' },
  { codigo: 495, descricao: 'Lempira (Honduras)',           sigla: 'HNL', nomeCampo: 'HNL - Lempira' },
  { codigo: 500, descricao: 'Leone (Serra Leoa)',           sigla: 'SLL', nomeCampo: 'SLL - Leone' },
  { codigo: 535, descricao: 'Libra Egípcia',               sigla: 'EGP', nomeCampo: 'EGP - Libra Egípcia' },
  { codigo: 540, descricao: 'Libra Esterlina',             sigla: 'GBP', nomeCampo: 'GBP - Libra Esterlina' },
  { codigo: 560, descricao: 'Libra Libanesa',              sigla: 'LBP', nomeCampo: 'LBP - Libra Libanesa' },
  { codigo: 575, descricao: 'Libra Síria',                 sigla: 'SYP', nomeCampo: 'SYP - Libra Síria' },
  { codigo: 622, descricao: 'Metical (Moçambique)',         sigla: 'MZN', nomeCampo: 'MZN - Metical' },
  { codigo: 630, descricao: 'Naira (Nigéria)',              sigla: 'NGN', nomeCampo: 'NGN - Naira' },
  { codigo: 635, descricao: 'Kwanza (Angola)',              sigla: 'AOA', nomeCampo: 'AOA - Kwanza' },
  { codigo: 640, descricao: 'Novo Dólar Taiwanês',         sigla: 'TWD', nomeCampo: 'TWD - Novo Dólar Taiwanês' },
  { codigo: 642, descricao: 'Nova Lira Turca',             sigla: 'TRY', nomeCampo: 'TRY - Nova Lira Turca' },
  { codigo: 660, descricao: 'Sol (Peru)',                   sigla: 'PEN', nomeCampo: 'PEN - Sol (Peru)' },
  { codigo: 680, descricao: "Pa'anga (Tonga)",              sigla: 'TOP', nomeCampo: "TOP - Pa'anga" },
  { codigo: 685, descricao: 'Pataca (Macau)',               sigla: 'MOP', nomeCampo: 'MOP - Pataca' },
  { codigo: 706, descricao: 'Peso Argentino',              sigla: 'ARS', nomeCampo: 'ARS - Peso Argentino' },
  { codigo: 715, descricao: 'Peso Chileno',                sigla: 'CLP', nomeCampo: 'CLP - Peso Chileno' },
  { codigo: 720, descricao: 'Peso Colombiano',             sigla: 'COP', nomeCampo: 'COP - Peso Colombiano' },
  { codigo: 730, descricao: 'Peso Dominicano',             sigla: 'DOP', nomeCampo: 'DOP - Peso Dominicano' },
  { codigo: 735, descricao: 'Peso Filipino',               sigla: 'PHP', nomeCampo: 'PHP - Peso Filipino' },
  { codigo: 741, descricao: 'Peso Mexicano',               sigla: 'MXN', nomeCampo: 'MXN - Peso Mexicano' },
  { codigo: 745, descricao: 'Peso Uruguaio',               sigla: 'UYU', nomeCampo: 'UYU - Peso Uruguaio' },
  { codigo: 755, descricao: 'Pula (Botsuana)',              sigla: 'BWP', nomeCampo: 'BWP - Pula' },
  { codigo: 766, descricao: 'Kwacha (Zâmbia)',              sigla: 'ZMW', nomeCampo: 'ZMW - Kwacha' },
  { codigo: 770, descricao: 'Quetzal (Guatemala)',          sigla: 'GTQ', nomeCampo: 'GTQ - Quetzal' },
  { codigo: 785, descricao: 'Rand (África do Sul)',         sigla: 'ZAR', nomeCampo: 'ZAR - Rand' },
  { codigo: 795, descricao: 'Yuan Chinês (Renminbi)',       sigla: 'CNY', nomeCampo: 'CNY - Yuan Chinês' },
  { codigo: 800, descricao: 'Rial Catariano',              sigla: 'QAR', nomeCampo: 'QAR - Rial Catariano' },
  { codigo: 805, descricao: 'Rial Omanense',               sigla: 'OMR', nomeCampo: 'OMR - Rial Omanense' },
  { codigo: 810, descricao: 'Rial Iemenita',               sigla: 'YER', nomeCampo: 'YER - Rial Iemenita' },
  { codigo: 815, descricao: 'Rial Iraniano',               sigla: 'IRR', nomeCampo: 'IRR - Rial Iraniano' },
  { codigo: 820, descricao: 'Riyal Saudita',               sigla: 'SAR', nomeCampo: 'SAR - Riyal Saudita' },
  { codigo: 825, descricao: 'Riel (Camboja)',               sigla: 'KHR', nomeCampo: 'KHR - Riel' },
  { codigo: 828, descricao: 'Ringgit (Malásia)',            sigla: 'MYR', nomeCampo: 'MYR - Ringgit' },
  { codigo: 830, descricao: 'Rublo Russo',                 sigla: 'RUB', nomeCampo: 'RUB - Rublo Russo' },
  { codigo: 840, descricao: 'Rúpia Mauriciana',            sigla: 'MUR', nomeCampo: 'MUR - Rúpia Mauriciana' },
  { codigo: 870, descricao: 'Rufiyaa (Maldivas)',           sigla: 'MVR', nomeCampo: 'MVR - Rufiyaa' },
  { codigo: 875, descricao: 'Rúpia Paquistanesa',          sigla: 'PKR', nomeCampo: 'PKR - Rúpia Paquistanesa' },
  { codigo: 880, descricao: 'Novo Shekel Israelense',      sigla: 'ILS', nomeCampo: 'ILS - Novo Shekel Israelense' },
  { codigo: 912, descricao: 'Tala (Samoa)',                 sigla: 'WST', nomeCampo: 'WST - Tala' },
  { codigo: 913, descricao: 'Tenge (Cazaquistão)',          sigla: 'KZT', nomeCampo: 'KZT - Tenge' },
  { codigo: 915, descricao: 'Tugrik (Mongólia)',            sigla: 'MNT', nomeCampo: 'MNT - Tugrik' },
  { codigo: 930, descricao: 'Won Sul-Coreano',             sigla: 'KRW', nomeCampo: 'KRW - Won Sul-Coreano' },
  { codigo: 946, descricao: 'Xelim Tanzaniano',            sigla: 'TZS', nomeCampo: 'TZS - Xelim Tanzaniano' },
  { codigo: 950, descricao: 'Xelim Queniano',              sigla: 'KES', nomeCampo: 'KES - Xelim Queniano' },
  { codigo: 955, descricao: 'Xelim Ugandês',               sigla: 'UGX', nomeCampo: 'UGX - Xelim Ugandês' },
]

/** Opções completas para GTColuna.moedas (tabela virtual) */
export const MOEDAS_SISCOMEX_OPCOES = MOEDAS_SISCOMEX.map(m => ({
  sigla: m.sigla,
  rotulo: m.nomeCampo,
}))
