"""Adiciona pedido.coluna_pai.* ao pt.json (one-shot, pode deletar depois)."""
import json, pathlib

PT = pathlib.Path("nucleo-global/Utilidades/Localization/locales/pt.json")
data = json.loads(PT.read_text("utf-8"))

keys = {
  "numero_pedido": "N\u00ba Pedido / N\u00ba do Item",
  "numero_pedido_titulo": "N\u00ba Pedido / N\u00ba do Item",
  "numero_pedido_desc": "N\u00famero do pedido (linha pai) ou N\u00ba do Item (linha filho)",
  "tipo_operacao": "Tipo de Opera\u00e7\u00e3o",
  "tipo_operacao_titulo": "Tipo de Opera\u00e7\u00e3o",
  "tipo_operacao_desc": "Importa\u00e7\u00e3o (Purchase Order) ou Exporta\u00e7\u00e3o (Sales Order)",
  "nome_exportador": "Nome do Exportador",
  "nome_exportador_titulo": "Nome do Exportador",
  "nome_exportador_desc": "Fornecedor/exportador estrangeiro na opera\u00e7\u00e3o de importa\u00e7\u00e3o",
  "nome_importador": "Nome do Importador",
  "nome_importador_titulo": "Nome do Importador",
  "nome_importador_desc": "Comprador/importador estrangeiro na opera\u00e7\u00e3o de exporta\u00e7\u00e3o",
  "nome_fabricante": "Nome do Fabricante",
  "nome_fabricante_titulo": "Nome do Fabricante",
  "nome_fabricante_desc": "Identifica\u00e7\u00e3o da origem produtiva",
  "referencia_importador": "Refer\u00eancia Importador",
  "referencia_importador_titulo": "Refer\u00eancia do Importador",
  "referencia_importador_desc": "C\u00f3digo de refer\u00eancia interna do importador para o pedido",
  "referencia_exportador": "Refer\u00eancia Exportador",
  "referencia_exportador_titulo": "Refer\u00eancia do Exportador",
  "referencia_exportador_desc": "C\u00f3digo de refer\u00eancia utilizado pelo exportador",
  "ncm": "NCM",
  "ncm_titulo": "NCM",
  "ncm_desc": "Nomenclatura Comum do Mercosul",
  "numero_proforma": "N\u00famero da Proforma",
  "numero_proforma_titulo": "N\u00famero da Proforma",
  "numero_proforma_desc": "Refer\u00eancia da Proforma Invoice vinculada",
  "numero_invoice": "N\u00famero da Invoice",
  "numero_invoice_titulo": "N\u00famero da Invoice",
  "numero_invoice_desc": "Identificador da Commercial Invoice (Fatura)",
  "incoterm": "Incoterm",
  "incoterm_titulo": "Incoterm",
  "incoterm_desc": "Regra de entrega: FOB, CIF, EXW, etc.",
  "valor_total_pedido": "Valor Total do Pedido",
  "valor_total_pedido_titulo": "Valor Total do Pedido",
  "valor_total_pedido_desc": "Calculado com base nos itens",
  "quantidade_total_inicial_pedido": "Qtd. Inicial do Pedido",
  "quantidade_total_inicial_pedido_titulo": "Qtd. Inicial do Pedido",
  "quantidade_total_inicial_pedido_desc": "Calculado com base nos itens",
  "quantidade_pronta_itens_pedido_total": "Qtd. Pronta do Pedido",
  "quantidade_pronta_itens_pedido_total_titulo": "Qtd. Pronta do Pedido",
  "quantidade_pronta_itens_pedido_total_desc": "Calculado com base nos itens",
  "saldo_itens_do_pedido": "Saldo do Pedido",
  "saldo_itens_do_pedido_titulo": "Saldo do Pedido",
  "quantidade_transferida_total": "Qtd. Transferida do Pedido",
  "quantidade_transferida_total_titulo": "Qtd. Transferida do Pedido",
  "quantidade_transferida_total_desc": "Soma da quantidade transferida de todos os itens do pedido.",
  "quantidade_cancelada_total_pedido": "Qtd. Cancelada do Pedido",
  "quantidade_cancelada_total_pedido_titulo": "Qtd. Cancelada do Pedido",
  "quantidade_cancelada_total_pedido_desc": "Total cancelado permanentemente nos itens do pedido.",
  "data_emissao_pedido": "Data P.O",
  "data_emissao_pedido_titulo": "Data do Pedido",
  "data_emissao_pedido_desc": "Data de registro ou emiss\u00e3o da Purchase Order",
  "status": "Status",
  "status_titulo": "Status do Pedido",
  "status_desc": "Ciclo de vida: Draft, Aberto, Em Transfer\u00eancia, Consolidado, Cancelado",
  "referencia_fabricante": "Refer\u00eancia do Fabricante",
  "referencia_fabricante_titulo": "Refer\u00eancia do Fabricante",
  "referencia_fabricante_desc": "C\u00f3digo de refer\u00eancia utilizado pelo fabricante",
  "cobertura_cambial": "Cobertura Cambial do Pedido",
  "cobertura_cambial_titulo": "Cobertura Cambial",
  "cobertura_cambial_desc": "Modalidade de cobertura cambial por item.",
  "condicao_pagamento_pedido": "Condi\u00e7\u00e3o de Pagamento do Pedido",
  "condicao_pagamento_pedido_titulo": "Condi\u00e7\u00e3o de Pagamento",
  "condicao_pagamento_pedido_desc": "Prazo e forma de pagamento acordados com o exportador.",
  "peso_liquido_total_pedido": "Peso L\u00edquido Total do Pedido",
  "peso_liquido_total_pedido_titulo": "Peso L\u00edquido Total do Pedido",
  "peso_liquido_total_pedido_desc": "Calculado com base nos itens",
  "peso_bruto_total_pedido": "Peso Bruto Total do Pedido",
  "peso_bruto_total_pedido_titulo": "Peso Bruto Total do Pedido",
  "peso_bruto_total_pedido_desc": "Calculado com base nos itens",
  "cubagem_total_pedido": "Cubagem Total do Pedido",
  "cubagem_total_pedido_titulo": "Cubagem Total do Pedido",
  "cubagem_total_pedido_desc": "Calculado com base nos itens",
  "data_prevista_pedido_pronto": "Data Prevista Pedido Pronto",
  "data_prevista_pedido_pronto_titulo": "Data Prevista \u2014 Pedido Pronto",
  "data_prevista_pedido_pronto_desc": "Data prevista para o pedido estar pronto para embarque",
  "data_confirmada_pedido_pronto": "Data Confirmada Pedido Pronto",
  "data_confirmada_pedido_pronto_titulo": "Data Confirmada \u2014 Pedido Pronto",
  "data_confirmada_pedido_pronto_desc": "Data confirmada para o pedido estar pronto",
  "data_meta_pedido_pronto": "Data Meta Pedido Pronto",
  "data_meta_pedido_pronto_titulo": "Data Meta \u2014 Pedido Pronto",
  "data_meta_pedido_pronto_desc": "Data meta definida pelo importador",
  "data_prevista_inspecao_pedido": "Data Prevista Inspe\u00e7\u00e3o do Pedido",
  "data_prevista_inspecao_pedido_titulo": "Data Prevista \u2014 Inspe\u00e7\u00e3o",
  "data_prevista_inspecao_pedido_desc": "Data prevista para inspe\u00e7\u00e3o pr\u00e9-embarque (PSI/ISF)",
  "data_confirmada_inspecao_pedido": "Data Confirmada Inspe\u00e7\u00e3o do Pedido",
  "data_confirmada_inspecao_pedido_titulo": "Data Confirmada \u2014 Inspe\u00e7\u00e3o",
  "data_confirmada_inspecao_pedido_desc": "Data confirmada para inspe\u00e7\u00e3o pr\u00e9-embarque",
  "data_meta_inspecao_pedido": "Data Meta Inspe\u00e7\u00e3o do Pedido",
  "data_meta_inspecao_pedido_titulo": "Data Meta \u2014 Inspe\u00e7\u00e3o",
  "data_meta_inspecao_pedido_desc": "Data meta para a inspe\u00e7\u00e3o do pedido",
  "data_prevista_coleta_pedido": "Data Prevista Coleta do Pedido",
  "data_prevista_coleta_pedido_titulo": "Data Prevista \u2014 Coleta",
  "data_prevista_coleta_pedido_desc": "Data prevista para coleta/retirada da mercadoria",
  "data_confirmada_coleta_pedido": "Data Confirmada Coleta do Pedido",
  "data_confirmada_coleta_pedido_titulo": "Data Confirmada \u2014 Coleta",
  "data_confirmada_coleta_pedido_desc": "Data confirmada para coleta/retirada da mercadoria",
  "data_meta_coleta_pedido": "Data Meta Coleta do Pedido",
  "data_meta_coleta_pedido_titulo": "Data Meta \u2014 Coleta",
  "data_meta_coleta_pedido_desc": "Data meta para a coleta do pedido",
  "data_consolidacao_pedido": "Data Consolida\u00e7\u00e3o do Pedido",
  "data_consolidacao_pedido_titulo": "Data de Consolida\u00e7\u00e3o do Pedido",
  "data_consolidacao_pedido_desc": "Data em que o pedido foi consolidado",
  "data_transferencia_saldo_pedido": "Dt Transfer\u00eancia Qtd. do Pedido",
  "data_transferencia_saldo_pedido_titulo": "Data de Transfer\u00eancia de Saldo",
  "data_transferencia_saldo_pedido_desc": "Data em que o saldo foi transferido",
  "pais_exportador": "Pa\u00eds do Exportador",
  "pais_exportador_titulo": "Pa\u00eds do Exportador",
  "pais_exportador_desc": "Pa\u00eds de origem do exportador/fornecedor",
  "estado_exportador": "Estado/Prov\u00edncia do Exportador",
  "estado_exportador_titulo": "Estado ou Prov\u00edncia do Exportador",
  "estado_exportador_desc": "Estado ou prov\u00edncia do exportador",
  "cidade_exportador": "Cidade do Exportador",
  "cidade_exportador_titulo": "Cidade do Exportador",
  "cidade_exportador_desc": "Cidade do exportador",
  "endereco_exportador": "Endere\u00e7o do Exportador",
  "endereco_exportador_titulo": "Endere\u00e7o do Exportador",
  "endereco_exportador_desc": "Endere\u00e7o completo do exportador/fornecedor",
  "zip_code_exportador": "Zipcode do Exportador",
  "zip_code_exportador_titulo": "Zip Code do Exportador",
  "zip_code_exportador_desc": "C\u00f3digo postal do exportador",
  "exportador_ou_fabricante": "Exportador/Fabricante?",
  "exportador_ou_fabricante_titulo": "Exportador ou Fabricante?",
  "exportador_ou_fabricante_desc": "Indica se o exportador \u00e9 tamb\u00e9m o fabricante",
  "relacao_exportador_fabricante": "Rela\u00e7\u00e3o Exportador e Fabricante",
  "relacao_exportador_fabricante_titulo": "Rela\u00e7\u00e3o entre Exportador e Fabricante",
  "relacao_exportador_fabricante_desc": "Tipo de rela\u00e7\u00e3o entre exportador e fabricante",
  "nome_contato_exportador": "Contato Exportador",
  "nome_contato_exportador_titulo": "Nome do Contato do Exportador",
  "nome_contato_exportador_desc": "Nome do contato principal no exportador",
  "email_contato_exportador": "Email do Exportador",
  "email_contato_exportador_titulo": "E-mail do Contato do Exportador",
  "email_contato_exportador_desc": "E-mail do contato principal",
  "whatsapp_contato_exportador": "Whatsapp do Exportador",
  "whatsapp_contato_exportador_titulo": "WhatsApp do Contato do Exportador",
  "whatsapp_contato_exportador_desc": "N\u00famero de WhatsApp do contato",
  "cargo_contato_exportador": "Cargo do Contato no Exportador",
  "cargo_contato_exportador_titulo": "Cargo do Contato do Exportador",
  "cargo_contato_exportador_desc": "Cargo ou fun\u00e7\u00e3o do contato no exportador",
  "departamento_contato_exportador": "Departamento do Contato no Exportador",
  "departamento_contato_exportador_titulo": "Departamento do Contato do Exportador",
  "departamento_contato_exportador_desc": "Departamento do contato no exportador",
  "pais_fabricante": "Pa\u00eds do Fabricante",
  "pais_fabricante_titulo": "Pa\u00eds do Fabricante",
  "pais_fabricante_desc": "Pa\u00eds onde o produto foi fabricado",
  "estado_fabricante": "Estado/Prov\u00edncia do Fabricante",
  "estado_fabricante_titulo": "Estado ou Prov\u00edncia do Fabricante",
  "estado_fabricante_desc": "Estado ou prov\u00edncia do fabricante",
  "cidade_fabricante": "Cidade do Fabricante",
  "cidade_fabricante_titulo": "Cidade do Fabricante",
  "cidade_fabricante_desc": "Cidade do fabricante",
  "endereco_fabricante": "Endere\u00e7o do Fabricante",
  "endereco_fabricante_titulo": "Endere\u00e7o do Fabricante",
  "endereco_fabricante_desc": "Endere\u00e7o completo do fabricante",
  "zip_code_fabricante": "Zipcode do Fabricante",
  "zip_code_fabricante_titulo": "Zip Code do Fabricante",
  "zip_code_fabricante_desc": "C\u00f3digo postal do fabricante",
  "anexo_pedido": "Anexo do Pedido",
  "anexo_pedido_titulo": "Anexo do Pedido",
  "anexo_pedido_desc": "Arquivo do pedido em PDF ou outro formato",
  "anexo_proforma": "Anexo da Proforma",
  "anexo_proforma_titulo": "Anexo da Proforma Invoice",
  "anexo_proforma_desc": "Arquivo da Proforma Invoice",
  "anexo_invoice": "Anexo da Invoice",
  "anexo_invoice_titulo": "Anexo da Invoice",
  "anexo_invoice_desc": "Arquivo da Commercial Invoice",
  "quantidade_volumes_pedido": "Quantidade de Volumes do Pedido",
  "quantidade_volumes_pedido_titulo": "Quantidade de Volumes Total do Pedido",
  "quantidade_volumes_pedido_desc": "N\u00famero total de volumes (caixas, pallets, etc.)",
  "data_documento_pedido": "Data do Documento Pedido",
  "data_documento_pedido_titulo": "Data do Documento Pedido",
  "data_documento_pedido_desc": "Data de emiss\u00e3o do documento do pedido",
  "data_proforma_invoice": "Data do Documento Proforma",
  "data_proforma_invoice_titulo": "Data da Proforma Invoice",
  "data_proforma_invoice_desc": "Data de emiss\u00e3o da Proforma Invoice",
  "data_invoice": "Data do Documento Invoice",
  "data_invoice_titulo": "Data da Invoice",
  "data_invoice_desc": "Data de emiss\u00e3o da Commercial Invoice"
}

data["pedido"]["coluna_pai"] = keys
PT.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", "utf-8")
print(f"OK {len(keys)} chaves adicionadas em pedido.coluna_pai")
