/**
 * dashboardCatalog.ts — Catálogo de campos do Dashboard BID Frete Internacional
 *
 * Cada campo é um CatalogField enriquecido com propriedades de visualização e semântica.
 */
export const DASHBOARD_CATALOG = [
    {
        key: 'saving_total',
        label: 'Saving Total (Ganho vs Meta)',
        productId: 'bid_frete',
        type: 'currency',
        aggregations: ['SUM'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'sum_currency',
        domain: 'cotacao',
        complementaryFields: ['valor_aprovado_usd', 'ganho_percentual_ganho_bid_frete_internacional'],
    },
    {
        key: 'valor_medio_ganho_bid_frete_internacional',
        label: 'Valor Médio Ganho',
        productId: 'bid_frete',
        type: 'currency',
        aggregations: ['AVG'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'sum_currency',
        domain: 'cotacao',
        complementaryFields: ['valor_aprovado_usd', 'saving_total'],
    },
    {
        key: 'cotacoes_status',
        label: 'Cotações por Status',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['COUNT'],
        permission: 'cotacao.read',
        chartTypes: ['DISTRIBUTION'],
        semanticType: 'count',
        domain: 'cotacao',
        complementaryFields: ['cotacoes_andamento', 'cotacoes_passadas'],
        dimension: 'status_cotacao',
        dimensionLabel: 'Status de Cotação',
    },
    {
        key: 'ganho_percentual_ganho_bid_frete_internacional',
        label: 'Ganho Percentual Médio',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['AVG'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE'],
        semanticType: 'ratio',
        domain: 'cotacao',
        complementaryFields: ['saving_total'],
    },
    {
        key: 'transit_time',
        label: 'Transit Time Médio (Dias)',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['AVG'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'count',
        domain: 'cotacao',
        complementaryFields: ['cotacoes_passadas'],
    },
    {
        key: 'volume_mensal',
        label: 'Volume Mensal de Cotações',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['COUNT'],
        permission: 'cotacao.read',
        chartTypes: ['LINE', 'BAR'],
        semanticType: 'count',
        domain: 'cotacao',
        complementaryFields: ['cotacoes_andamento', 'cotacoes_passadas'],
    },
    {
        key: 'cotacoes_andamento',
        label: 'Cotações em Andamento',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['COUNT'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'count',
        domain: 'cotacao',
        complementaryFields: ['cotacoes_passadas', 'valor_andamento_usd'],
    },
    {
        key: 'cotacoes_passadas',
        label: 'Cotações Passadas',
        productId: 'bid_frete',
        type: 'number',
        aggregations: ['COUNT'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'count',
        domain: 'cotacao',
        complementaryFields: ['cotacoes_andamento', 'valor_aprovado_usd'],
    },
    {
        key: 'valor_andamento_usd',
        label: 'Valor Total em Andamento (USD)',
        productId: 'bid_frete',
        type: 'currency',
        aggregations: ['SUM'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'sum_currency',
        domain: 'cotacao',
        complementaryFields: ['valor_aprovado_usd', 'cotacoes_andamento'],
    },
    {
        key: 'valor_aprovado_usd',
        label: 'Valor Total Aprovado (USD)',
        productId: 'bid_frete',
        type: 'currency',
        aggregations: ['SUM'],
        permission: 'cotacao.read',
        chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
        semanticType: 'sum_currency',
        domain: 'cotacao',
        complementaryFields: ['valor_andamento_usd', 'cotacoes_passadas', 'saving_total'],
    },
];
export const CATALOG_BY_KEY = Object.fromEntries(DASHBOARD_CATALOG.map(f => [f.key, f]));
//# sourceMappingURL=dashboardCatalog.js.map