/**
 * Catálogo de campos do Dashboard configurável — visão fornecedor BID Frete Internacional
 */

import type { EnrichedCatalogField } from '@nucleo/dashboard'

export const DASHBOARD_CATALOG_FORNECEDOR: EnrichedCatalogField[] = [
  {
    key: 'cotacoes_pendentes_visao_fornecedor',
    label: 'Cotações aguardando resposta',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_enviadas_visao_fornecedor', 'disparos_recebidos_visao_fornecedor'],
  },
  {
    key: 'propostas_enviadas_visao_fornecedor',
    label: 'Propostas enviadas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_aprovadas_visao_fornecedor', 'taxa_aprovacao_visao_fornecedor'],
  },
  {
    key: 'propostas_aprovadas_visao_fornecedor',
    label: 'Propostas aprovadas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_reprovadas_visao_fornecedor', 'taxa_aprovacao_visao_fornecedor'],
  },
  {
    key: 'propostas_em_analise_visao_fornecedor',
    label: 'Propostas em análise',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['cotacoes_pendentes_visao_fornecedor'],
  },
  {
    key: 'propostas_reprovadas_visao_fornecedor',
    label: 'Propostas reprovadas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_aprovadas_visao_fornecedor'],
  },
  {
    key: 'disparos_recebidos_visao_fornecedor',
    label: 'Cotações recebidas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['taxa_resposta_visao_fornecedor'],
  },
  {
    key: 'taxa_resposta_visao_fornecedor',
    label: 'Taxa de resposta (%)',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['AVG'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE'],
    semanticType: 'ratio',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['disparos_recebidos_visao_fornecedor'],
  },
  {
    key: 'taxa_aprovacao_visao_fornecedor',
    label: 'Taxa de aprovação (%)',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['AVG'],
    permission: 'cotacao.read',
    chartTypes: ['KPI_CARD', 'LINE'],
    semanticType: 'ratio',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_enviadas_visao_fornecedor'],
  },
  {
    key: 'cotacoes_status',
    label: 'Funil das propostas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['DISTRIBUTION'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['cotacoes_pendentes_visao_fornecedor', 'propostas_enviadas_visao_fornecedor'],
    dimension: 'status_funil_fornecedor',
    dimensionLabel: 'Etapa do funil',
  },
  {
    key: 'volume_mensal',
    label: 'Volume mensal de propostas',
    productId: 'bid_frete',
    type: 'number',
    aggregations: ['COUNT'],
    permission: 'cotacao.read',
    chartTypes: ['LINE', 'BAR'],
    semanticType: 'count',
    domain: 'visao_fornecedor_bid_frete_internacional',
    complementaryFields: ['propostas_enviadas_visao_fornecedor'],
  },
]

export const CATALOG_FORNECEDOR_BY_KEY = Object.fromEntries(
  DASHBOARD_CATALOG_FORNECEDOR.map(f => [f.key, f]),
)

export const STATUS_LABELS_FORNECEDOR_DASHBOARD: Record<string, string> = {
  AGUARDANDO_RESPOSTA: 'Aguardando resposta',
  EM_ANALISE: 'Em análise',
  APROVADA: 'Aprovada',
  REPROVADA: 'Reprovada',
  EXPIRADA: 'Expirada',
}
